set -x
#GCC_DIR=../../toolchain_stm32_macos/gcc-arm-none-eabi-10-2020-q4-major/bin/
GCC_DIR=../../toolchain_essentials/bin/
$GCC_DIR/arm-none-eabi-gcc -mcpu=cortex-m0plus -c -x assembler-with-cpp -MMD -MP -MF"build/startup_stm32g030c8tx.d" -MT"build/startup_stm32g030c8tx.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/startup_stm32g030c8tx.o" "Src/startup_stm32g030c8tx.s"
$GCC_DIR/arm-none-eabi-gcc "../global_variables.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/global_variables.d" -MT"build/global_variables.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/global_variables.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../RS485.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/RS485.d" -MT"build/RS485.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/RS485.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../debug_uart.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/debug_uart.d" -MT"build/debug_uart.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/debug_uart.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../error_handling.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/error_handling.d" -MT"build/error_handling.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/error_handling.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../error_text.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/error_test.d" -MT"build/error_text.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/error_text.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../mosfets.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/mosfets.d" -MT"build/mosfets.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/mosfets.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "Src/leds.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/leds.d" -MT"build/leds.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/leds.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "Src/main.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/main.d" -MT"build/main.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/main.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "Src/syscalls.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/syscalls.d" -MT"build/syscalls.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/syscalls.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "Src/sysmem.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/sysmem.d" -MT"build/sysmem.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/sysmem.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "Src/system_stm32g0xx.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/system_stm32g0xx.d" -MT"build/system_stm32g0xx.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/system_stm32g0xx.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../unique_id.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/unique_id.d" -MT"build/unique_id.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/unique_id.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../settings.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/settings.d" -MT"build/settings.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/settings.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../product_info.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/product_info.d" -MT"build/product_info.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/product_info.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc "../device_status.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32G030xx -c -ISrc -I../../Drivers/STM32G0xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32G0xx/Include -I../../Drivers/CMSIS/Include -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"build/device_status.d" -MT"build/device_statud.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "build/device_status.o" -DZ_AXIS
$GCC_DIR/arm-none-eabi-gcc -o "build/servomotor_bootloader.elf" @"objects.list" -mcpu=cortex-m0plus -T"STM32G030C8TX_FLASH.ld" --specs=nosys.specs -Wl,-Map="build/firmware_STM32G030.map" -Wl,--gc-sections -static --specs=nano.specs -mfloat-abi=soft -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
$GCC_DIR/arm-none-eabi-size   build/servomotor_bootloader.elf 
$GCC_DIR/arm-none-eabi-objdump -h -S  build/servomotor_bootloader.elf  > "build/servomotor_bootloader.list"
$GCC_DIR/arm-none-eabi-objcopy  -O binary  build/servomotor_bootloader.elf  "build/servomotor_bootloader.bin"
