N_COMMUTATION_SUB_STEPS_SHIFT_RIGHT = 8
N_COMMUTATION_STEPS                 = 360
N_COMMUTATION_SUB_STEPS             = (1 << N_COMMUTATION_SUB_STEPS_SHIFT_RIGHT)
ONE_REVOLUTION_ELECTRICAL_CYCLES    = 50
ONE_REVOLUTION_HALL_SENSOR_CYCLES   = 25