- product: M1
  versions:
  - version: V26
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/dark_template.html
    picture: https://raw.githubusercontent.com/tomrodinger/servomotor/main/Pictures/servomotor1/top2.jpg
    description: This is a servo motor made with a 3-phase DC brushless motor. It can be controlled over an RS485 interface.
    schematic: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/PCB/V10/schematic.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/V1/user-manual.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor1/V26
    firmwares:
    - version: 0.2.3
      compatibility: 0
      date: September 9, 2021
      description: Initial firmware for this product
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R1/firmware/0.2.3.firmware
      sha256: 43f6df3f42ae0582b1331c3ebc3eec1662dc2a7740039b04128bb06d5931dac9
- product: M2
  versions:
  - version: V4
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/light_template.html
    picture: https://raw.githubusercontent.com/tomrodinger/servomotor/main/Pictures/servomotor2/back.jpg
    description: This is a servo motor made with a 3-phase stepper motor. It can be controlled over an RS485 interface.
    schematic: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/PCB/V10/schematic.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/V1/user-manual.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor2/V4
    firmwares:
    - version: 0.2.3
      compatibility: 0
      date: September 29, 2022
      description: Initial firmware for the servo motor
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/firmware/servo-motor-fw.firmware
      sha256: 43f6df3f42ae0582b1331c3ebc3eec1662dc2a7740039b04128bb06d5931dac9
  - version: V5
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/light_template.html
    picture: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/V2/pcb_picture_top.jpg
    description: This product is able to control a servo motor, improved performance
    schematic: https://raw.githubusercontent.com/tomrodinger/line_following_robot/main/PCB/V10/schematic.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/V2/user-manual.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor2/V5
    firmwares:
    - version: 0.2.3
      compatibility: 0
      date: September 29, 2022
      description: Initial firmware for the servo motor
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/firmware/servo-motor-fw.bin
      sha256: 43f6df3f42ae0582b1331c3ebc3eec1662dc2a7740039b04128bb06d5931dac9
- product: M3
  versions:
  - version: V5
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/light_template.html
    picture: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/V2/pcb_picture_top.jpg
    description: This product is a Servomotor with 3-in-1 integrated motor + motor driver + motion controller in a stepper motor form factor
    schematic: https://raw.githubusercontent.com/tomrodinger/servomotor/PCB/Servomotor3/V5/schematic/sch-M3-V5-24-01-24.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/V2/user-manual.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor3/V5
    firmwares:
    - version: 0.2.3
      compatibility: 0
      date: February 24, 2024
      description: Firmware for the servomotor#3 (model M3)
      url: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/firmware/servo-motor-fw.bin
      sha256: 43f6df3f42ae0582b1331c3ebc3eec1662dc2a7740039b04128bb06d5931dac9
  - version: V7
    type: full_product
    web_page_template: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/light_template.html
    picture: https://raw.githubusercontent.com/tomrodinger/servomotor/main/Pictures/servomotor3/servomotor3.jpg
    description: This product is a Servomotor with 3-in-1 integrated motor + motor driver + motion controller in a stepper motor form factor
    schematic: https://raw.githubusercontent.com/tomrodinger/servomotor/PCB/Servomotor3/V7/schematic/M3-V7-index-schTop.pdf
    user_manual: https://raw.githubusercontent.com/vladsomai/test_line_following_robot/main/Products/R2/V2/user-manual.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor3/V7
    firmwares:
    - version: 0.8.10
      compatibility: 0
      date: June 16, 2024
      description: Firmware for the servomotor#3 (model M3)
      url: https://raw.githubusercontent.com/tomrodinger/servomotor/firmware_releases/motor_firmware_M3_V2_fw0.8.10.firmware
      sha256: d885ba6749f00a8a02585b920c0d4b9f7dfbc1503d7419428e9e2f59e8cda579
  - version: V11
    type: full_product
    web_page_template: https://cdn.jsdelivr.net/gh/vladsomai/test_line_following_robot@main/Products/light_template.html
    picture: 
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153751.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153753.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153754.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_202507141537551.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153757.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153758.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153759.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153937.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153938.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153942.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153943.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153944.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153945.jpg
    - https://raw.githubusercontent.com/tomrodinger/servomotor/refs/heads/main/Pictures/servomotor3/M17-48%20motor/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20250714153946.jpg
    description: This product is a Servomotor with 3-in-1 integrated motor + motor driver + motion controller in a Nema17 form factor
    schematic: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/PCB/Servomotor3/V11/schematic/V11-index-schTop.pdf
    user_manual: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/servomotor_datasheets/servomotor_datasheet_v1.1_Dec_5_2024.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor3/V11
    firmwares:
    - version: 0.9.1.0
      compatibility: 3
      date: January 3, 2025
      description: Firmware for the servomotor model M3
      url: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/firmware/firmware_releases/servomotor_M3_fw0.9.1.0_scc3_hwV11.firmware
      sha256: 69236b0e362e57d8a63f25a6fdcb3934c096c4e738471be43146689e24e82764
  - version: 1.2
    type: full_product
    web_page_template: https://cdn.jsdelivr.net/gh/vladsomai/test_line_following_robot@main/Products/light_template.html
    picture: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/Pictures/servomotor3/servomotor3 family2.jpg
    description: This product is a Servomotor with 3-in-1 integrated motor + motor driver + motion controller in a Nema17 form factor
    schematic: https://raw.githubusercontent.com/tomrodinger/servomotor/main/PCB/Servomotor3/1.2/schematic/1.2-index-schTop.pdf
    user_manual: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/servomotor_datasheets/servomotor_datasheet_v1.1_Dec_5_2024.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor3/1.2
    firmwares:
    - version: 0.11.0.0
      compatibility: 3
      date: June 12, 2025
      description: Firmware for the servomotor model M3
      url: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/firmware/firmware_releases/servomotor_M3_fw0.11.0.0_scc3_hw1.2.firmware
      sha256: 01307afe2ed455a570d6dfdaf240b033c80e0eb4dbec9fdb2a3f93c1819222df
  - version: 1.3
    type: full_product
    web_page_template: https://cdn.jsdelivr.net/gh/vladsomai/test_line_following_robot@main/Products/light_template.html
    picture: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/Pictures/servomotor3/servomotor3 family2.jpg
    description: This product is a Servomotor with 3-in-1 integrated motor + motor driver + motion controller in a Nema17 form factor
    schematic: https://raw.githubusercontent.com/tomrodinger/servomotor/main/PCB/Servomotor3/1.3/schematic/1.3-index-schTop.pdf
    user_manual: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/servomotor_datasheets/servomotor_datasheet_v1.1_Dec_5_2024.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor3/1.3
    firmwares:
    - version: 0.11.0.1
      compatibility: 3
      date: June 25, 2025
      description: Firmware for the servomotor model M3
      url: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/firmware/firmware_releases/servomotor_M3_fw0.11.0.1_scc3_hw1.3.firmware
      sha256: 4efa761edb1f6337da95eed12d4ba78fd727c98d0487c39e6eddbb9f083282f6
    - version: 0.12.0.0
      compatibility: 3
      date: July 2, 2025
      description: Firmware for the servomotor model M3
      url: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/firmware/firmware_releases/servomotor_M3_fw0.12.0.0_scc3_hw1.3.firmware
      sha256: dea721652cec3d5684bcfaa999c7f371926dc2a224e210119199dd5080b798b3
- product: M17
  versions:
  - version: '1.0'
    type: full_product
    web_page_template: https://cdn.jsdelivr.net/gh/vladsomai/test_line_following_robot@main/Products/light_template.html
    picture: 
    - https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/Pictures/servomotor3/servomotor3 family2.jpg
    - https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/Pictures/servomotor3/servomotor3 with a connector1.jpg
    description: This product is a Servomotor with 3-in-1 integrated motor + motor driver + motion controller in a Nema17 form factor
    schematic: https://raw.githubusercontent.com/tomrodinger/servomotor/main/PCB/Servomotor3/1.0/schematic/1.0-index-schTop.pdf
    user_manual: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/servomotor_datasheets/servomotor_datasheet_latest.pdf
    tutorial: https://tutorial.gearotons.com/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor3/1.0
    firmwares:
    - version: 0.13.0.0
      compatibility: 3
      date: August 27, 2025
      description: Firmware for the servomotor model M17
      url: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/firmware/firmware_releases/servomotor_M17_fw0.13.0.0_scc3_hw1.0.firmware
      sha256: 0c6ddd1d88d84a304e057422fabfa612cdfebd2ee5ee2bee8ca8846a1b399bb8
  - version: 1.3
    type: full_product
    web_page_template: https://cdn.jsdelivr.net/gh/vladsomai/test_line_following_robot@main/Products/light_template.html
    picture: 
    - https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/Pictures/servomotor3/servomotor3 family2.jpg
    - https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/Pictures/servomotor3/servomotor3 with a connector1.jpg
    description: This product is a Servomotor with 3-in-1 integrated motor + motor driver + motion controller in a Nema17 form factor
    schematic: https://raw.githubusercontent.com/tomrodinger/servomotor/main/PCB/Servomotor3/1.3/schematic/1.3-index-schTop.pdf
    user_manual: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/servomotor_datasheets/servomotor_datasheet_v1.2_Jul_12_2025.pdf
    tutorial: https://servo-tutorial.netlify.app/
    github: https://github.com/tomrodinger/servomotor/tree/main/PCB/Servomotor3/1.3
    firmwares:
    - version: 0.13.0.0
      compatibility: 3
      date: August 27, 2025
      description: Firmware for the servomotor model M17
      url: https://cdn.jsdelivr.net/gh/tomrodinger/servomotor@main/firmware/firmware_releases/servomotor_M17_fw0.13.0.0_scc3_hw1.3.firmware
      sha256: 0c6ddd1d88d84a304e057422fabfa612cdfebd2ee5ee2bee8ca8846a1b399bb8
