#ifndef AUTO_GENERATED_UNIT_CONVERSIONS_H
#define AUTO_GENERATED_UNIT_CONVERSIONS_H

/*
  AutoGeneratedUnitConversions.h

  Declarations for enumerations and conversion functions for
  time, position, velocity, acceleration, current, voltage,
  and temperature, using a simplified ArduinoEmulator so you
  can test on a Mac.
*/

#include "ArduinoEmulator.h"

// ---------------------------------------------------
// 1) Enumerations
// ---------------------------------------------------
enum class TimeUnit {
    SECONDS,
    MILLISECONDS,
    MINUTES,
    TIMESTEPS
};

enum class PositionUnit {
    SHAFT_ROTATIONS,
    DEGREES,
    RADIANS,
    ENCODER_COUNTS
};

enum class VelocityUnit {
    ROTATIONS_PER_SECOND,
    RPM,
    DEGREES_PER_SECOND,
    RADIANS_PER_SECOND,
    COUNTS_PER_SECOND
};

enum class AccelerationUnit {
    ROTATIONS_PER_SECOND_SQUARED,
    RPM_PER_SECOND,
    DEGREES_PER_SECOND_SQUARED,
    RADIANS_PER_SECOND_SQUARED,
    COUNTS_PER_SECOND_SQUARED
};

enum class CurrentUnit {
    MILLIAMPS,
    AMPS
};

enum class VoltageUnit {
    MILLIVOLTS,
    VOLTS
};

enum class TemperatureUnit {
    CELSIUS,
    FAHRENHEIT,
    KELVIN
};

// ---------------------------------------------------
// 2) Function Prototypes
// ---------------------------------------------------

float convertTime(float value, TimeUnit fromUnit, TimeUnit toUnit);
float convertPosition(float value, PositionUnit fromUnit, PositionUnit toUnit);
float convertVelocity(float value, VelocityUnit fromUnit, VelocityUnit toUnit);
float convertAcceleration(float value, AccelerationUnit fromUnit, AccelerationUnit toUnit);
float convertCurrent(float value, CurrentUnit fromUnit, CurrentUnit toUnit);
float convertVoltage(float value, VoltageUnit fromUnit, VoltageUnit toUnit);
float convertTemperature(float value, TemperatureUnit fromUnit, TemperatureUnit toUnit);

#endif // AUTO_GENERATED_UNIT_CONVERSIONS_H