g++ -std=c++11 -DREQUIRE_SERIAL_PORT test_one_move.cpp ArduinoEmulator.cpp ServomotorCommands.cpp Communication.cpp Utils.cpp DataTypes.cpp AutoGeneratedUnitConversions.cpp -o test_one_move
g++ -std=c++11 -DREQUIRE_SERIAL_PORT test_one_move_two_motors.cpp ArduinoEmulator.cpp ServomotorCommands.cpp Communication.cpp Utils.cpp DataTypes.cpp AutoGeneratedUnitConversions.cpp -o test_one_move_two_motors
g++ -std=c++17 test_unit_conversions.cpp AutoGeneratedUnitConversions.cpp ArduinoEmulator.cpp -o test_unit_conversions
g++ -std=c++11 -DREQUIRE_SERIAL_PORT test_get_temperature.cpp ArduinoEmulator.cpp ServomotorCommands.cpp Communication.cpp Utils.cpp DataTypes.cpp AutoGeneratedUnitConversions.cpp -o test_get_temperature
