#!/bin/bash

# Common source files needed by all tests
COMMON_SOURCES="ArduinoEmulator.cpp Servomotor.cpp Communication.cpp Utils.cpp DataTypes.cpp AutoGeneratedUnitConversions.cpp test_framework.cpp"

# Common compiler flags
COMMON_FLAGS="-std=c++17"

# Build tests that require serial port
Echo "Compiling example_one_move"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT example_one_move.cpp $COMMON_SOURCES -o example_one_move
Echo "Compiling example_one_move_two_motors"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT example_one_move_two_motors.cpp $COMMON_SOURCES -o example_one_move_two_motors
Echo "Compiling example_multi_move"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT example_multi_move.cpp $COMMON_SOURCES -o example_multi_move
Echo "Compiling test_get_temperature"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT test_get_temperature.cpp $COMMON_SOURCES -o test_get_temperature
Echo "Compiling test_enable_disable_mosfets"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT test_enable_disable_mosfets.cpp $COMMON_SOURCES -o test_enable_disable_mosfets
Echo "Compiling test_emergency_stop"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT test_emergency_stop.cpp $COMMON_SOURCES -o test_emergency_stop
Echo "Compiling test_move_with_velocity"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT test_move_with_velocity.cpp $COMMON_SOURCES -o test_move_with_velocity
Echo "Compiling test_move_with_acceleration"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT test_move_with_acceleration.cpp $COMMON_SOURCES -o test_move_with_acceleration
Echo "Compiling test_get_comprehensive_position"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT test_get_comprehensive_position.cpp $COMMON_SOURCES -o test_get_comprehensive_position
Echo "Compiling test_multi_move"
g++ $COMMON_FLAGS -DREQUIRE_SERIAL_PORT test_multi_move.cpp $COMMON_SOURCES -o test_multi_move

# Build tests that don't require serial port
g++ $COMMON_FLAGS test_unit_conversions.cpp $COMMON_SOURCES -o test_unit_conversions
