g++ -std=c++11 test_one_move.cpp ArduinoEmulator.cpp ServomotorCommands.cpp Communication.cpp Utils.cpp DataTypes.cpp AutoGeneratedUnitConversions.cpp -o test_one_move
g++ -std=c++11 test_one_move_two_motors.cpp ArduinoEmulator.cpp ServomotorCommands.cpp Communication.cpp Utils.cpp DataTypes.cpp AutoGeneratedUnitConversions.cpp -o test_one_move_two_motors

