// Servomotor.h
// This file was autogenerated by generate_command_code.py on Mar 6 2025 20:42:41
// Do not edit manually. If changes are needed, modify the generator program instead.

#ifndef SERVOMOTOR_H
#define SERVOMOTOR_H

#ifdef ARDUINO
#include <Arduino.h>
#endif
#include "Communication.h"
#include "Commands.h"
#include "DataTypes.h"
#include "Utils.h"
#include "AutoGeneratedUnitConversions.h"

// Payload and Response Structures

// Structure for Trapezoid move command payload
typedef struct __attribute__((__packed__)) {
    int32_t displacement;
    uint32_t duration;
} trapezoidMovePayload;

// Structure for Set maximum velocity command payload
typedef struct __attribute__((__packed__)) {
    uint32_t maximumVelocity;
} setMaximumVelocityPayload;

// Structure for Go to position command payload
typedef struct __attribute__((__packed__)) {
    int32_t position;
    uint32_t duration;
} goToPositionPayload;

// Structure for Set maximum acceleration command payload
typedef struct __attribute__((__packed__)) {
    uint32_t maximumAcceleration;
} setMaximumAccelerationPayload;

// Structure for Capture hall sensor data command payload
typedef struct __attribute__((__packed__)) {
    uint8_t dataType;
} captureHallSensorDataPayload;

// Structure for Get current time command response
typedef struct __attribute__((__packed__)) {
    uint64_t currentTime;
} getCurrentTimeResponse;

// Structure for Time sync command payload
typedef struct __attribute__((__packed__)) {
    uint64_t masterTime;
} timeSyncPayload;

// Structure for Time sync command response
typedef struct __attribute__((__packed__)) {
    int32_t timeError;
    uint16_t rccIcscr;
} timeSyncResponse;

// Structure for Homing command payload
typedef struct __attribute__((__packed__)) {
    int32_t maxDistance;
    uint32_t maxDuration;
} homingPayload;

// Structure for Get hall sensor position command response
typedef struct __attribute__((__packed__)) {
    int64_t hallSensorPosition;
} getHallSensorPositionResponse;

// Structure for Get status command response
typedef struct __attribute__((__packed__)) {
    uint8_t statusFlags;
    uint8_t fatalErrorCode;
} StatusResponse;

// Structure for Move with acceleration command payload
typedef struct __attribute__((__packed__)) {
    int32_t acceleration;
    uint32_t timeSteps;
} moveWithAccelerationPayload;

// Structure for Detect devices command response
typedef struct __attribute__((__packed__)) {
    uint64_t uniqueId;
    uint8_t alias;
    uint32_t crc;
} detectDevicesResponse;

// Structure for Set device alias command payload
typedef struct __attribute__((__packed__)) {
    uint64_t uniqueId;
    uint8_t alias;
} setDeviceAliasPayload;

// Structure for Get product info command response
typedef struct __attribute__((__packed__)) {
    char productCode[8];
    uint8_t firmwareCompatibility;
    uint32_t hardwareVersion;
    uint32_t serialNumber;
    uint64_t uniqueId;
    uint32_t reserved;
} getProductInfoResponse;

// Structure for Firmware upgrade command payload
typedef struct __attribute__((__packed__)) {
    uint8_t firmwarePage[2058];
} firmwareUpgradePayload;

// Structure for Get product description command response
typedef struct __attribute__((__packed__)) {
    char productDescription[32];
} getProductDescriptionResponse;

// Structure for Move with velocity command payload
typedef struct __attribute__((__packed__)) {
    int32_t velocity;
    uint32_t duration;
} moveWithVelocityPayload;

// Structure for Set maximum motor current command payload
typedef struct __attribute__((__packed__)) {
    uint16_t motorCurrent;
    uint16_t regenerationCurrent;
} setMaximumMotorCurrentPayload;

// Structure for multi-move list item with raw internal units
typedef struct {
    int32_t value;  // acceleration or velocity value (internal units)
    uint32_t timeSteps;  // duration in time steps (internal units)
} multiMoveList_t;

// Structure for multi-move list item with user-friendly units
typedef struct {
    float value;  // velocity or acceleration in user units
    float duration;  // duration in user units (seconds, milliseconds, etc.)
} multiMoveListConverted_t;

// Structure for Multi-move command payload
typedef struct __attribute__((__packed__)) {
    uint8_t multiMoveCount;
    uint32_t multiMoveTypes;
    multiMoveList_t multiMoveList[32];
} multiMovePayload;

// Structure for Set safety limits command payload
typedef struct __attribute__((__packed__)) {
    int64_t lowerLimit;
    int64_t upperLimit;
} setSafetyLimitsPayload;

// Structure for Ping command payload
typedef struct __attribute__((__packed__)) {
    uint8_t pingData[10];
} pingPayload;

// Structure for Ping command response
typedef struct __attribute__((__packed__)) {
    uint8_t responsePayload[10];
} pingResponse;

// Structure for Control hall sensor statistics command payload
typedef struct __attribute__((__packed__)) {
    uint8_t control;
} controlHallSensorStatisticsPayload;

// Structure for Get hall sensor statistics command response
typedef struct __attribute__((__packed__)) {
    uint16_t maxHall1;
    uint16_t maxHall2;
    uint16_t maxHall3;
    uint16_t minHall1;
    uint16_t minHall2;
    uint16_t minHall3;
    uint64_t sumHall1;
    uint64_t sumHall2;
    uint64_t sumHall3;
    uint32_t measurementCount;
} getHallSensorStatisticsResponse;

// Structure for Test mode command payload
typedef struct __attribute__((__packed__)) {
    uint8_t testMode;
} testModePayload;

// Structure for Get comprehensive position command response
typedef struct __attribute__((__packed__)) {
    int64_t commandedPosition;
    int64_t hallSensorPosition;
    int32_t externalEncoderPosition;
} getComprehensivePositionResponse;

// Structure for Get supply voltage command response
typedef struct __attribute__((__packed__)) {
    uint16_t supplyVoltage;
} getSupplyVoltageResponse;

// Structure for Get max PID error command response
typedef struct __attribute__((__packed__)) {
    int32_t minPidError;
    int32_t maxPidError;
} getMaxPidErrorResponse;

// Structure for Vibrate command payload
typedef struct __attribute__((__packed__)) {
    uint8_t vibrationLevel;
} vibratePayload;

// Structure for Identify command payload
typedef struct __attribute__((__packed__)) {
    uint64_t uniqueId;
} identifyPayload;

// Structure for Get temperature command response
typedef struct __attribute__((__packed__)) {
    int16_t temperature;
} getTemperatureResponse;

// Structure for Set PID constants command payload
typedef struct __attribute__((__packed__)) {
    uint32_t kP;
    uint32_t kI;
    uint32_t kD;
} setPIDConstantsPayload;

// Structure for Set max allowable position deviation command payload
typedef struct __attribute__((__packed__)) {
    int64_t maxAllowablePositionDeviation;
} setMaxAllowablePositionDeviationPayload;

// Structure for Get debug values command response
typedef struct __attribute__((__packed__)) {
    int64_t maxAcceleration;
    int64_t maxVelocity;
    int64_t currentVelocity;
    int32_t measuredVelocity;
    uint32_t nTimeSteps;
    int64_t debugValue1;
    int64_t debugValue2;
    int64_t debugValue3;
    int64_t debugValue4;
    uint16_t allMotorControlCalculationsProfilerTime;
    uint16_t allMotorControlCalculationsProfilerMaxTime;
    uint16_t getSensorPositionProfilerTime;
    uint16_t getSensorPositionProfilerMaxTime;
    uint16_t computeVelocityProfilerTime;
    uint16_t computeVelocityProfilerMaxTime;
    uint16_t motorMovementCalculationsProfilerTime;
    uint16_t motorMovementCalculationsProfilerMaxTime;
    uint16_t motorPhaseCalculationsProfilerTime;
    uint16_t motorPhaseCalculationsProfilerMaxTime;
    uint16_t motorControlLoopPeriodProfilerTime;
    uint16_t motorControlLoopPeriodProfilerMaxTime;
    uint16_t hallSensor1Voltage;
    uint16_t hallSensor2Voltage;
    uint16_t hallSensor3Voltage;
    uint32_t commutationPositionOffset;
    uint8_t motorPhasesReversed;
    int32_t maxHallPositionDelta;
    int32_t minHallPositionDelta;
    int32_t averageHallPositionDelta;
    uint8_t motorPwmVoltage;
} getDebugValuesResponse;

// Structure for converted comprehensive position values
typedef struct {
    float commandedPosition;
    float hallSensorPosition;
    float externalEncoderPosition;
} getComprehensivePositionResponseConverted;

// Structure for converted max PID error values
typedef struct {
    float minPidError;
    float maxPidError;
} getMaxPidErrorResponseConverted;

class Servomotor {
public:
    Servomotor(uint8_t alias = 'X', HardwareSerial& serialPort = Serial1);
    void setAlias(uint8_t new_alias);
    uint8_t getAlias();
    void openSerialPort();
    int getError() const;

    // Unit settings
    void setTimeUnit(TimeUnit unit);
    void setPositionUnit(PositionUnit unit);
    void setVelocityUnit(VelocityUnit unit);
    void setAccelerationUnit(AccelerationUnit unit);
    void setCurrentUnit(CurrentUnit unit);
    void setVoltageUnit(VoltageUnit unit);
    void setTemperatureUnit(TemperatureUnit unit);

    void disableMosfets();
    void enableMosfets();
    void trapezoidMoveRaw(int32_t displacement, uint32_t duration);
    void trapezoidMove(float displacement, float duration);
    void setMaximumVelocityRaw(uint32_t maximumVelocity);
    void setMaximumVelocity(float maximumVelocity);
    void goToPositionRaw(int32_t position, uint32_t duration);
    void goToPosition(float position, float duration);
    void setMaximumAccelerationRaw(uint32_t maximumAcceleration);
    void setMaximumAcceleration(float maximumAcceleration);
    void startCalibration();
    uint8_t captureHallSensorData(uint8_t dataType);
    void resetTime();
    getCurrentTimeResponse getCurrentTimeRaw();
    float getCurrentTime();
    timeSyncResponse timeSync(uint64_t masterTime);
    uint8_t getNumberOfQueuedItems();
    void emergencyStop();
    void zeroPosition();
    void homingRaw(int32_t maxDistance, uint32_t maxDuration);
    void homing(float maxDistance, float maxDuration);
    getHallSensorPositionResponse getHallSensorPositionRaw();
    float getHallSensorPosition();
    StatusResponse getStatus();
    void goToClosedLoop();
    uint32_t getUpdateFrequency();
    void moveWithAccelerationRaw(int32_t acceleration, uint32_t timeSteps);
    void moveWithAcceleration(float acceleration, float timeSteps);
    detectDevicesResponse detectDevices();
    detectDevicesResponse detectDevicesGetAnotherResponse();
    void setDeviceAlias(uint64_t uniqueId, uint8_t alias);
    getProductInfoResponse getProductInfo();
    void firmwareUpgrade(uint8_t firmwarePage[2058]);
    getProductDescriptionResponse getProductDescription();
    uint32_t getFirmwareVersion();
    void moveWithVelocityRaw(int32_t velocity, uint32_t duration);
    void moveWithVelocity(float velocity, float duration);
    void systemReset();
    void setMaximumMotorCurrentRaw(uint16_t motorCurrent, uint16_t regenerationCurrent);
    void setMaximumMotorCurrent(float motorCurrent, float regenerationCurrent);
    void multiMoveRaw(uint8_t multiMoveCount, uint32_t multiMoveTypes, multiMoveList_t* multiMoveList);
    void multiMove(uint8_t multiMoveCount, uint32_t multiMoveTypes, multiMoveListConverted_t* multiMoveList);
    void setSafetyLimitsRaw(int64_t lowerLimit, int64_t upperLimit);
    void setSafetyLimits(float lowerLimit, float upperLimit);
    pingResponse ping(uint8_t pingData[10]);
    void controlHallSensorStatistics(uint8_t control);
    getHallSensorStatisticsResponse getHallSensorStatistics();
    getHallSensorPositionResponse getPositionRaw();
    float getPosition();
    uint8_t readMultipurposeBuffer();
    void testMode(uint8_t testMode);
    getComprehensivePositionResponse getComprehensivePositionRaw();
    getComprehensivePositionResponseConverted getComprehensivePosition();
    getSupplyVoltageResponse getSupplyVoltageRaw();
    float getSupplyVoltage();
    getMaxPidErrorResponse getMaxPidErrorRaw();
    getMaxPidErrorResponseConverted getMaxPidError();
    void vibrate(uint8_t vibrationLevel);
    void identify(uint64_t uniqueId);
    getTemperatureResponse getTemperatureRaw();
    float getTemperature();
    void setPIDConstants(uint32_t kP, uint32_t kI, uint32_t kD);
    void setMaxAllowablePositionDeviationRaw(int64_t maxAllowablePositionDeviation);
    void setMaxAllowablePositionDeviation(float maxAllowablePositionDeviation);
    getDebugValuesResponse getDebugValues();

private:
    uint8_t _alias;
    Communication _comm;
    int _errno;

    // Unit settings
    TimeUnit m_timeUnit = TimeUnit::TIMESTEPS;
    PositionUnit m_positionUnit = PositionUnit::SHAFT_ROTATIONS;
    VelocityUnit m_velocityUnit = VelocityUnit::ROTATIONS_PER_SECOND;
    AccelerationUnit m_accelerationUnit = AccelerationUnit::ROTATIONS_PER_SECOND_SQUARED;
    CurrentUnit m_currentUnit = CurrentUnit::INTERNAL_CURRENT_UNITS;
    VoltageUnit m_voltageUnit = VoltageUnit::MILLIVOLTS;
    TemperatureUnit m_temperatureUnit = TemperatureUnit::CELSIUS;

    bool _initialized;
    void ensureInitialized();
};

#endif // SERVOMOTOR_H
