#ifndef __COMMUTATION_TABLE__
#define __COMMUTATION_TABLE__

// * * * DO NOT EDIT * * * Instead, edit the program that autogenerates this
// This file was autogenerated by executing: BLDC_sin_lookup_table.py M3
// (possibly via autogenerate.py)
// Generated on: Mar 11 2025 20:27:03

#define N_COMMUTATION_STEPS 64
#define N_COMMUTATION_SUB_STEPS 1024
#define ONE_REVOLUTION_ELECTRICAL_CYCLES 50
#define ONE_REVOLUTION_MICROSTEPS 3276800

#endif
