#ifndef COMMANDS_H_
#define COMMANDS_H_

#define DISABLE_MOSFETS_COMMAND 0
#define ENABLE_MOSFETS_COMMAND 1
#define TRAPEZOID_MOVE_COMMAND 2
#define SET_MAX_VELOCITY_COMMAND 3
#define GO_TO_POSITION_COMMAND 4
#define SET_MAX_ACCELERATION_COMMAND 5
#define START_CALIBRATION_COMMAND 6
#define CAPTURE_HALL_SENSOR_DATA_COMMAND 7
#define RESET_TIME_COMMAND 8
#define GET_CURRENT_TIME_COMMAND 9
#define TIME_SYNC_COMMAND 10
#define GET_N_ITEMS_IN_QUEUE_COMMAND 11
#define EMERGENCY_STOP_COMMAND 12
#define ZERO_POSITION_COMMAND 13
#define HOMING_COMMAND 14
#define GET_HALL_SENSOR_POSITION_COMMAND 15
#define GET_STATUS_COMMAND 16
#define GO_TO_CLOSED_LOOP_COMMAND 17
#define GET_UPDATE_FREQUENCY_COMMAND 18
#define MOVE_WITH_ACCELERATION_COMMAND 19
#define DETECT_DEVICES_COMMAND 20
#define SET_DEVICE_ALIAS_COMMAND 21
#define GET_PRODUCT_INFO_COMMAND 22
#define FIRMWARE_UPGRADE_COMMAND 23
#define GET_PRODUCT_DESCRIPTION_COMMAND 24
#define GET_FIRMWARE_VERSION_COMMAND 25
#define MOVE_WITH_VELOCITY_COMMAND 26
#define SYSTEM_RESET_COMMAND 27
#define SET_MAXIMUM_MOTOR_CURRENT 28
#define MULTI_MOVE_COMMAND 29
#define SET_SAFETY_LIMITS_COMMAND 30
#define PING_COMMAND 31
#define CONTROL_HALL_SENSOR_STATISTICS_COMMAND 32
#define GET_HALL_SENSOR_STATISTICS_COMMAND 33
#define GET_POSITION_COMMAND 34
#define READ_MULTIPURPOSE_BUFFER_COMMAND 35
#define TEST_MODE_COMMAND 36
#define GET_COMPREHENSIVE_POSITION_COMMAND 37
#define GET_SUPPLY_VOLTAGE_COMMAND 38
#define GET_MAX_PID_ERROR_COMMAND 39
#define VIBRATE_COMMAND 40
#define IDENTIFY_COMMAND 41
#define GET_TEMPERATURE_COMMAND 42
#define SET_PID_CONSTANTS_COMMAND 43
#define SET_MAX_ALLOWABLE_POSITION_DEVIATION 44
//#define SET_MAX_TEMPERATURE_COMMAND xx
#define GET_DEBUG_VALUES_COMMAND 252
#define ADD_TO_QUEUE_TEST_COMMAND 253

#endif