#include "test_registry.h"

// Execution order rationale:
//  - pure-computation tests first (no motor needed),
//  - cheap reads next, then calibration EARLY so every later closed-loop /
//    position-dependent test runs against a freshly calibrated motor
//    (mirrors the Python suite's ordering),
//  - motion depth, stress, and behavior tests in the middle,
//  - fleet tests (multi_device, broadcast) near the end,
//  - addressing LAST (it changes the alias + reboots the motor twice).
// Timeouts are generous: a timeout marks the test CRASH and the suite moves on.
const TestDef TF_TESTS[] = {
    //  name                    fn                        knownBugs         timeout  needsMotor
    { "unit_conversions",      tm_unit_conversions,      "",                  60, false },
    { "units_roundtrip",       tm_units_roundtrip,       "",                  60, false },
    { "product_info",          tm_product_info,          "",                  90, true  },
    { "temperature",           tm_temperature,           "",                  60, true  },
    { "telemetry",             tm_telemetry,             "",                 150, true  },
    { "system_status",         tm_system_status,         "",                 150, true  },
    { "status_matrix",         tm_status_matrix,         "",                  90, true  },
    { "comms",                 tm_comms,                 "",                 150, true  },
    { "ping_stress",           tm_ping_stress,           "",                  90, true  },
    { "wrong_addressing",      tm_wrong_addressing,      "",                  60, true  },
    { "time",                  tm_time,                  "",                 150, true  },
    { "calibration",           tm_calibration,           "",                 240, true  },
    { "diagnostics",           tm_diagnostics,           "",                 240, true  },
    { "motion_basic",          tm_motion_basic,          "",                 240, true  },
    { "move_velocity",         tm_move_velocity,         "",                 120, true  },
    { "move_accel",            tm_move_accel,            "",                 120, true  },
    { "multimove",             tm_multimove,             "",                 240, true  },
    { "fast_short_moves",      tm_fast_short_moves,      "",                 120, true  },
    { "queue_stress",          tm_queue_stress,          "",                 150, true  },
    { "emergency_stop",        tm_emergency_stop,        "",                  90, true  },
    { "comm_during_motion",    tm_comm_during_motion,    "",                 120, true  },
    { "velocity_accuracy",     tm_velocity_accuracy,     "",                 120, true  },
    { "voltage_under_load",    tm_voltage_under_load,    "",                  90, true  },
    { "settings",              tm_settings,              "",                 240, true  },
    { "safety_pid",            tm_safety_pid,            "",                 240, true  },
    { "safety_fence",          tm_safety_fence,          "",                 150, true  },
    { "pid_dynamics",          tm_pid_dynamics,          "",                 180, true  },
    { "closed_loop",           tm_closed_loop,           "",                 180, true  },
    { "homing",                tm_homing,                "",                 300, true  },
    { "comprehensive_position",tm_comprehensive_position,"",                  90, true  },
    { "actuators",             tm_actuators,             "",                 150, true  },
    { "error_injection",       tm_error_injection,       "",                 150, true  },
    { "varlen_bugs",           tm_varlen_bugs,           "",                 240, true  },
    { "enable_reliability",    tm_enable_reliability,    "",                 120, true  },
    { "multi_device",          tm_multi_device,          "",                 300, true  },
    { "broadcast",             tm_broadcast,             "",                 150, true  },
    { "addressing",            tm_addressing,            "",                 240, true  },

    // ---- Round 3: edge-case / bug-hunting modules ----
    // Numeric / queue / protocol boundaries first (mostly no motion), then
    // state-machine + physical edges, then the heavier real-usage patterns.
    { "overflow_guards",       tm_overflow_guards,       "",                 120, true  },
    { "float_edges",           tm_float_edges,           "",                 150, true  },
    { "dwell_and_tiny",        tm_dwell_and_tiny,        "",                 150, true  },
    { "queue_edges",           tm_queue_edges,           "",                 300, true  },
    { "multimove_edges",       tm_multimove_edges,       "",                 120, true  },
    { "limit_boundaries",      tm_limit_boundaries,      "",                 150, true  },
    { "goto_edges",            tm_goto_edges,            "",                 180, true  },
    { "position_frames",       tm_position_frames,       "",                 240, true  },
    { "raw_protocol",          tm_raw_protocol,          "",                 120, true  },
    { "payload_size_attacks",  tm_payload_size_attacks,  "",                 120, true  },
    { "bad_command_byte",      tm_bad_command_byte,      "",                  90, true  },
    { "uid_edges",             tm_uid_edges,             "",                 120, true  },
    { "timeout_recovery",      tm_timeout_recovery,      "",                 180, true  },
    { "rapid_fire",            tm_rapid_fire,            "",                 300, true  },
    { "mosfet_interactions",   tm_mosfet_interactions,   "",                 180, true  },
    { "settings_persistence",  tm_settings_persistence,  "",                 240, true  },
    { "limit_reset_edges",     tm_reset_edges,           "",                 180, true  },
    { "fatal_state_matrix",    tm_fatal_state_matrix,    "",                 150, true  },
    { "calibration_rejections",tm_calibration_rejections,"",                 180, true  },
    { "homing_edges",          tm_homing_edges,          "",                 180, true  },
    { "bootloader_window",     tm_bootloader_window,     "",                 120, true  },
    { "version_info",          tm_version_info_consistency,"",                60, true  },
    { "sensor_consistency",    tm_sensor_consistency,    "",                 180, true  },
    { "actuator_edges",        tm_actuator_edges,        "",                 150, true  },
    { "alias_edges",           tm_alias_edges,           "",                 300, true  },
    { "two_motors",            tm_two_motors,            "",                 300, true  },
    { "planner_arithmetic",   tm_planner_arithmetic,    "",                 300, true  },
    { "move_composition",     tm_move_composition,      "",                 600, true  },
    { "unit_equivalence",     tm_unit_equivalence,      "",                 600, true  },
    { "queue_accounting",     tm_queue_accounting,      "",                 600, true  },
    { "setting_timing",       tm_setting_timing,        "",                 600, true  },
    { "determinism",          tm_determinism,           "",                1200, true  },
    { "error_taxonomy",       tm_error_taxonomy,        "",                1200, true  },
    { "position_accumulator", tm_position_accumulator,  "",                1800, true  },
    { "crc32_matrix",         tm_crc32_matrix,          "",                 900, true  },
    { "multimove_bitmask",    tm_multimove_bitmask,     "",                1200, true  },
    { "stop_semantics",       tm_stop_semantics,        "",                1200, true  },
    { "time_domain",          tm_time_domain,           "",                 900, true  },
    { "fatal_state_commands", tm_fatal_state_commands,  "",                1200, true  },
    { "queue_underrun",       tm_queue_underrun,        "",                1800, true  },
    { "readonly_purity",      tm_readonly_purity,       "",                1800, true  },
    { "move_type_equivalence",tm_move_type_equivalence, "",                1800, true  },
    { "soak",                 tm_soak,                  "",                2700, true  },
    { "command_state_matrix", tm_command_state_matrix,  "",                2700, true  },
    { "duration_extremes",    tm_duration_extremes,     "",                1800, true  },
    { "reset_completeness",   tm_reset_completeness,    "",                1800, true  },
    { "deviation_tracking",   tm_deviation_tracking,    "",                1800, true  },
    { "acceleration_move_semantics", tm_acceleration_move_semantics, "",                 1800, true  },
    { "current_and_pid_settings", tm_current_and_pid_settings, "",                 1800, true  },
    { "device_identity",         tm_device_identity,        "",                 1800, true  },
    { "diagnostics_readouts",    tm_diagnostics_readouts,   "",                 1800, true  },
    { "goto_absolute_semantics", tm_goto_absolute_semantics, "",                 1800, true  },
    { "hall_capture",            tm_hall_capture,           "",                 1800, true  },
    { "multimove_capacity",      tm_multimove_capacity,     "",                 1800, true  },
    { "safety_fence_arithmetic", tm_safety_fence_arithmetic, "",                 1800, true  },
    { "telemetry_conversions",   tm_telemetry_conversions,  "",                 1800, true  },
    { "velocity_move_semantics", tm_velocity_move_semantics, "",                 1800, true  },
    { "zero_position_semantics", tm_zero_position_semantics, "",                 1800, true  },
    { "communication_statistics", tm_communication_statistics, "",                 1800, true  },
    { "indicator_commands",      tm_indicator_commands,     "",                 1800, true  },
    { "multipurpose_buffer",     tm_multipurpose_buffer,    "",                 1800, true  },
    { "packet_size_encoding",    tm_packet_size_encoding,   "",                 1800, true  },
    { "position_source_consistency", tm_position_source_consistency, "",                 1800, true  },
    { "queue_ordering",          tm_queue_ordering,         "",                 1800, true  },
    { "status_flag_semantics",   tm_status_flag_semantics,  "",                 1800, true  },
    { "time_sync_protocol",      tm_time_sync_protocol,     "",                 1800, true  },
    { "boundary_value_sweep",    tm_boundary_value_sweep,   "",                 1800, true  },
    { "command_latency_profile", tm_command_latency_profile, "",                 1800, true  },
    { "concurrent_command_pressure", tm_concurrent_command_pressure, "",                 1800, true  },
    { "error_code_reachability", tm_error_code_reachability, "",                 1800, true  },
    { "firmware_compat_gating",  tm_firmware_compat_gating, "",                 1800, true  },
    { "homing_arithmetic",       tm_homing_arithmetic,      "",                 1800, true  },
    { "motion_timing_precision", tm_motion_timing_precision, "",                 1800, true  },
    { "position_far_field",      tm_position_far_field,     "",                 1800, true  },
    { "power_on_defaults",       tm_power_on_defaults,      "",                 1800, true  },
    { "realistic_motion_patterns", tm_realistic_motion_patterns, "",                 1800, true  },
    { "recovery_sequences",      tm_recovery_sequences,     "",                 1800, true  },
    { "repeated_command_idempotence", tm_repeated_command_idempotence, "",                 1800, true  },
    { "response_field_integrity", tm_response_field_integrity, "",                 1800, true  },
    { "settings_interaction_matrix", tm_settings_interaction_matrix, "",                 1800, true  },
    { "streaming_motion",        tm_streaming_motion,       "",                 1800, true  },
    { "unit_extreme_values",     tm_unit_extreme_values,    "",                 1800, true  },
};

const int TF_N_TESTS = sizeof(TF_TESTS) / sizeof(TF_TESTS[0]);
