#include "tf_framework.h"

// ---------------------------------------------------------------------------
// tm_dwell_and_tiny.cpp
//
// Edge cases of the trapezoid-move PLANNER around ZERO displacement and
// SUB-COUNT moves. All motion is closed-loop and gentle.
//
// GROUND TRUTH (firmware/Src/motor_control.c, verified line-by-line):
//   * add_trapezoid_move_to_queue(disp, time) (motor_control.c:1938):
//       - fatal_error(ERROR_PARAMETER_OUT_OF_RANGE) ONLY if total_time == 0.
//         A zero DISPLACEMENT with nonzero time is fully accepted.
//       - It calls compute_trapezoid_move() then add_to_queue() THREE times
//         (accel / coast / decel). compute_trapezoid_move(0, T) yields
//         acceleration == 0 (numerator delta_d == 0), with delta_t1 nonzero,
//         so the coast+ramp items still occupy the queue for the whole T time
//         steps. Zero acceleration => the commanded-position integrator
//         (current_position_i96) never advances: a zero-displacement move is a
//         genuine TIMED DWELL that holds position and blocks the queue ~T.
//   * Time base: CONVERSION_FACTOR_SECONDS == 31250 (AutoGeneratedUnitConversions.h)
//     => 1.0 s == 31250 time steps, and the control loop runs at 31250 Hz, so a
//     31250-time-step dwell drains in ~1.000 s.
//   * Position scale: COUNTS_PER_REVOLUTION == 3276800 counts/rotation.
//     0.0000001 rot == 0.32768 counts. The library converts float->raw by
//     TRUNCATION ((int32_t)(displacement_internal), Servomotor.cpp:192), so
//     0.32768 -> 0: a sub-count fractional move degenerates into a zero-
//     displacement dwell (accepted, no motion).
//   * "Get position" (main.c:443) returns get_motor_position() ==
//     current_position_i96.position, i.e. the COMMANDED setpoint integrated from
//     the queue. It is deterministic: identical trapezoids each advance it by an
//     identical integer, and a dwell (accel 0) advances it by exactly 0.
//   * A move over ZERO time is a separate error path (fatal 34) and is NOT
//     exercised here (this module never sends a zero-duration move).
//
// Error code referenced (verified against
//   python_programs/servomotor/error_codes.json): 34 == ERROR_PARAMETER_OUT_OF_RANGE
//   (not asserted directly; we only assert that the accepted cases stay at 0).
//
// STATUS FLAG BITS (common_source_files/device_status.h):
//   STATUS_CLOSED_LOOP_FLAG_BIT == 2, STATUS_MOTOR_BUSY_FLAG_BIT == 6.
//
// SAFETY:
//   * Closed loop via goToClosedLoop() (enables MOSFETs internally,
//     motor_control.c:963); gentle engagement (~0.01 deg). Zeroing is done
//     AFTER engagement, never before.
//   * Every commanded move is a trapezoid that begins and ends at REST (zero
//     velocity), so the queue may be abandoned/reset at any point with no
//     lingering commanded velocity. Peak speed <= ~0.2 rot/s (<< 3 rot/s).
//     Net travel across the whole module is < ~0.35 rotation (<< 1 rotation).
//   * No test-mode command is ever sent (values 10..13 are never touched).
//   * tfGetMotor() is unique-ID (extended) addressed -> collision-safe on the
//     39-motor rack; nothing is broadcast that solicits multi-device responses.
//   * No raw Serial1 frame injection: all traffic goes through the library.
//   * Every wait loop is bounded by a millis() timeout.
// ---------------------------------------------------------------------------

static const int      NORMAL_RESET_DELAY_MS = 1500;   // wait after a plain reset
static const int      SETTLE_MS             = 250;    // let a finished move settle

static const int32_t  COUNTS_PER_REV        = 3276800; // AutoGeneratedUnitConversions.h
static const uint32_t TS_PER_SEC            = 31250;   // CONVERSION_FACTOR_SECONDS

static const uint16_t CLOSED_LOOP_MASK      = (uint16_t)(1 << 2); // STATUS_CLOSED_LOOP_FLAG_BIT
static const uint16_t MOTOR_BUSY_MASK       = (uint16_t)(1 << 6); // STATUS_MOTOR_BUSY_FLAG_BIT

// Drain any bytes left on the motor UART so a stale reply can't desync the next read.
static void drainSerial() {
    for (uint32_t tf_drain_t0 = millis(); Serial1.available() && (millis() - tf_drain_t0) < 500; ) Serial1.read();  // bounded drain (hang-proof)
}

// systemReset + settle + drain: guaranteed clean, known starting state.
static void cleanReset(Servomotor* motor) {
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);  // no response during reset; don't check errors
    drainSerial();
}

// Latched fatal error code via Get status (answered even in the fatal state).
// Returns 0xFF on a comms-layer failure so "no info" is distinguishable from code 0.
static uint8_t readFatal(Servomotor* motor) {
    getStatusResponse st = motor->getStatus();
    if (motor->getError() != 0) {
        printf("  (getStatus comms error: %d)\n", motor->getError());
        return 0xFF;
    }
    return st.fatalErrorCode;
}

// Current queue depth; 0xFF on a comms error.
static uint8_t readDepth(Servomotor* motor) {
    uint8_t n = motor->getNQueuedItems();
    if (motor->getError() != 0) {
        printf("  (getNQueuedItems comms error: %d)\n", motor->getError());
        return 0xFF;
    }
    return n;
}

// Poll the queue until empty or timeout. Returns true if it drained; *elapsedMs
// gets the wall-clock time from call entry to the moment depth hit 0.
static bool waitForQueueEmpty(Servomotor* motor, uint32_t timeoutMs, uint32_t* elapsedMs) {
    uint32_t start = millis();
    while (millis() - start < timeoutMs) {
        uint8_t n = motor->getNQueuedItems();
        if (motor->getError() == 0 && n == 0) {
            if (elapsedMs) *elapsedMs = millis() - start;
            return true;
        }
        delay(10);
    }
    if (elapsedMs) *elapsedMs = millis() - start;
    return false;
}

// Poll status until closed-loop is engaged and the motor is no longer busy.
static bool waitForClosedLoop(Servomotor* motor, uint32_t timeoutMs) {
    uint32_t start = millis();
    while (millis() - start < timeoutMs) {
        getStatusResponse st = motor->getStatus();
        if (motor->getError() == 0 &&
            (st.statusFlags & CLOSED_LOOP_MASK) &&
            !(st.statusFlags & MOTOR_BUSY_MASK)) {
            return true;
        }
        delay(20);
    }
    return false;
}

void tm_dwell_and_tiny(void) {
    Serial.println("test_ard_dwell_and_tiny: BEGIN\n");

    Servomotor* motor = tfGetMotor();

    // -----------------------------------------------------------------------
    // Clean, known starting state, then engage closed loop.
    // -----------------------------------------------------------------------
    cleanReset(motor);

    uint8_t startFatal = readFatal(motor);
    printf("Fatal code after reset: %d\n", startFatal);
    TEST_RESULT("DT No fatal error after reset", startFatal == 0);

    motor->setTimeUnit(TimeUnit::SECONDS);
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);

    motor->goToClosedLoop();     // enables MOSFETs internally; gentle engagement
    checkMotorError(*motor, "goToClosedLoop");
    bool inClosedLoop = waitForClosedLoop(motor, 6000);
    printf("Closed loop engaged: %d\n", (int)inClosedLoop);
    TEST_RESULT("DT Reached closed loop, motor idle", inClosedLoop);
    if (!inClosedLoop) {
        // Motor not calibrated / closed loop unavailable: motion asserts would
        // cascade meaninglessly. Clean up and bail out of the module.
        printf("DT closed loop NOT reached -- skipping motion sections, cleaning up\n");
        motor->systemReset();
        delay(1500);
        for (uint32_t t0 = millis(); Serial1.available() && (millis() - t0) < 500; ) Serial1.read();
        return;
    }

    motor->zeroPosition();       // zero AFTER engaging, per bench know-how
    checkMotorError(*motor, "zeroPosition");
    delay(SETTLE_MS);
    drainSerial();

    // =======================================================================
    // (a) ZERO-DISPLACEMENT trapezoidMove(0.0, 1.0 s) == a timed DWELL.
    //     Accepted (no fatal error), occupies the queue for ~1 s, holds position.
    // =======================================================================
    printf("\n--- (a) zero-displacement dwell: trapezoidMove(0.0, 1.0 s) ---\n");

    int64_t posBeforeDwell = motor->getPositionRaw();
    (void)motor->getError();

    motor->trapezoidMove(0.0f, 1.0f);     // disp 0, time 31250 steps -> accepted dwell
    (void)motor->getError();

    // Queue must be nonzero WHILE the dwell is executing (read promptly).
    uint8_t depthDuring = readDepth(motor);
    printf("Queue depth during dwell = %d (expect nonzero)\n", depthDuring);

    uint8_t dwellFatal = readFatal(motor);
    // Zero displacement + nonzero time never trips ERROR_PARAMETER_OUT_OF_RANGE
    // (motor_control.c:1944 only guards total_time == 0).
    TEST_RESULT("DT-a Zero-displacement move accepted (no fatal error)", dwellFatal == 0);
    TEST_RESULT("DT-a Queue nonzero while dwell runs",
                depthDuring != 0xFF && depthDuring > 0);

    uint32_t dwellMs = 0;
    bool dwellDrained = waitForQueueEmpty(motor, 3000, &dwellMs);
    printf("Dwell drained=%d in %lu ms (expect ~1000)\n",
           (int)dwellDrained, (unsigned long)dwellMs);
    TEST_RESULT("DT-a Dwell queue drains to empty", dwellDrained);
    // ~1.000 s = 31250 steps at 31250 Hz. Window is ~1 s +-30% widened upward
    // only for the 10 ms poll + comms latency (asymmetric on the high side).
    TEST_RESULT("DT-a Dwell occupies queue ~1 s",
                dwellDrained && dwellMs >= 700 && dwellMs <= 1400);

    delay(SETTLE_MS);
    int64_t posAfterDwell = motor->getPositionRaw();
    (void)motor->getError();
    int64_t dwellDelta = posAfterDwell - posBeforeDwell;
    printf("Dwell position delta = %ld counts (expect 0)\n", (long)dwellDelta);
    // accel == 0 => commanded integrator does not move.
    TEST_RESULT("DT-a Dwell holds position (|delta| <= 1 count)",
                dwellDelta >= -1 && dwellDelta <= 1);

    // =======================================================================
    // (b) 1-COUNT raw move: trapezoidMoveRaw(1, 31250). Accepted; commanded
    //     position advances by ~1 count. NOTE (firmware): with the default
    //     accel/velocity limits the planner's integer acceleration for a single
    //     count over a full second rounds toward 0, so the realized advance may
    //     be 0 as well as 1 -- both are inside the +-2 tolerance the spec allows.
    // =======================================================================
    printf("\n--- (b) 1-count move: trapezoidMoveRaw(1, 31250) ---\n");

    int64_t posBeforeTiny = motor->getPositionRaw();
    (void)motor->getError();

    motor->trapezoidMoveRaw(1, TS_PER_SEC);   // 1 count over 1.0 s
    (void)motor->getError();

    uint8_t tinyFatal = readFatal(motor);
    TEST_RESULT("DT-b 1-count move accepted (no fatal error)", tinyFatal == 0);

    uint32_t tinyMs = 0;
    bool tinyDrained = waitForQueueEmpty(motor, 3000, &tinyMs);
    printf("1-count move drained=%d in %lu ms\n",
           (int)tinyDrained, (unsigned long)tinyMs);
    TEST_RESULT("DT-b 1-count move queue drains to empty", tinyDrained);

    delay(SETTLE_MS);
    int64_t posAfterTiny = motor->getPositionRaw();
    (void)motor->getError();
    int64_t tinyDelta = posAfterTiny - posBeforeTiny;
    printf("1-count position delta = %ld counts (expect ~1, +-2)\n", (long)tinyDelta);
    // Advance is small and non-negative; spec tolerance is ~1 +-2 -> [-1, 3].
    TEST_RESULT("DT-b Position advances ~1 count (delta in [-1,3])",
                tinyDelta >= -1 && tinyDelta <= 3);

    // =======================================================================
    // (c) SUB-COUNT fractional move: trapezoidMove(0.0000001 rot, 1.0 s).
    //     0.0000001 rot * 3276800 = 0.32768 counts -> truncates to 0 -> dwell.
    //     Accepted, no error, |delta| <= 1 count.
    // =======================================================================
    printf("\n--- (c) sub-count move: trapezoidMove(0.0000001 rot, 1.0 s) ---\n");

    int64_t posBeforeFrac = motor->getPositionRaw();
    (void)motor->getError();

    motor->trapezoidMove(0.0000001f, 1.0f);   // 0.32768 counts -> truncates to 0
    (void)motor->getError();

    uint8_t fracFatal = readFatal(motor);
    TEST_RESULT("DT-c Sub-count move accepted (no fatal error)", fracFatal == 0);

    uint32_t fracMs = 0;
    bool fracDrained = waitForQueueEmpty(motor, 3000, &fracMs);
    printf("Sub-count move drained=%d in %lu ms\n",
           (int)fracDrained, (unsigned long)fracMs);
    TEST_RESULT("DT-c Sub-count move queue drains to empty", fracDrained);

    delay(SETTLE_MS);
    int64_t posAfterFrac = motor->getPositionRaw();
    (void)motor->getError();
    int64_t fracDelta = posAfterFrac - posBeforeFrac;
    printf("Sub-count position delta = %ld counts (expect 0 or 1)\n", (long)fracDelta);
    TEST_RESULT("DT-c Sub-count rounds to <= 1 count (|delta| <= 1)",
                fracDelta >= -1 && fracDelta <= 1);

    // =======================================================================
    // (d) DWELL BETWEEN two REAL moves. Baseline: one 0.1-rot move advances the
    //     commanded integrator by a fixed integer d1 (~327680 counts). Then run
    //     [0.1 rot][dwell 1 s][0.1 rot]: the sequence takes ~3 s (dwell holds the
    //     queue in the middle) and the net advance equals EXACTLY 2*d1 -- both
    //     real moves execute in order and the dwell contributes nothing.
    // =======================================================================
    printf("\n--- (d) baseline: single 0.1-rot move ---\n");

    int64_t posBeforeBase = motor->getPositionRaw();
    (void)motor->getError();

    motor->trapezoidMove(0.1f, 1.0f);         // gentle: peak ~0.2 rot/s
    (void)motor->getError();
    uint32_t baseMs = 0;
    bool baseDrained = waitForQueueEmpty(motor, 3000, &baseMs);
    delay(SETTLE_MS);
    int64_t posAfterBase = motor->getPositionRaw();
    (void)motor->getError();
    int64_t d1 = posAfterBase - posBeforeBase;
    printf("Baseline 0.1-rot delta = %ld counts (expect ~%d)\n",
           (long)d1, COUNTS_PER_REV / 10);
    TEST_RESULT("DT-d Baseline 0.1-rot move drains", baseDrained);
    // 0.1 rot == 327680 counts; allow +-200 counts for planner integer rounding.
    TEST_RESULT("DT-d Baseline 0.1-rot move advanced ~327680 counts",
                d1 > (COUNTS_PER_REV / 10 - 200) && d1 < (COUNTS_PER_REV / 10 + 200));

    uint8_t baseFatal = readFatal(motor);
    TEST_RESULT("DT-d Baseline move left no fatal error", baseFatal == 0);

    printf("\n--- (d) sequence: [0.1 rot][dwell 1 s][0.1 rot] ---\n");

    int64_t posBeforeSeq = motor->getPositionRaw();
    (void)motor->getError();

    motor->trapezoidMove(0.1f, 1.0f);   // real move 1
    (void)motor->getError();
    motor->trapezoidMove(0.0f, 1.0f);   // dwell in the middle
    (void)motor->getError();
    motor->trapezoidMove(0.1f, 1.0f);   // real move 2
    (void)motor->getError();

    uint8_t seqFatal = readFatal(motor);
    TEST_RESULT("DT-d Three-item sequence accepted (no fatal error)", seqFatal == 0);

    uint32_t seqMs = 0;
    bool seqDrained = waitForQueueEmpty(motor, 6000, &seqMs);
    printf("Sequence drained=%d in %lu ms (expect ~3000)\n",
           (int)seqDrained, (unsigned long)seqMs);
    TEST_RESULT("DT-d Sequence drains to empty", seqDrained);
    // move+dwell+move = ~3.0 s; the dwell in the middle is what pushes it past
    // the ~2 s of the two real moves alone.
    TEST_RESULT("DT-d Sequence takes ~3 s (dwell occupies the middle)",
                seqDrained && seqMs >= 2300 && seqMs <= 4200);

    delay(SETTLE_MS);
    int64_t posAfterSeq = motor->getPositionRaw();
    (void)motor->getError();
    int64_t dSeq = posAfterSeq - posBeforeSeq;
    printf("Sequence net delta = %ld counts (expect 2*d1 = %ld)\n",
           (long)dSeq, (long)(2 * d1));
    // Commanded integrator is deterministic: two identical 0.1-rot moves == 2*d1
    // exactly; the dwell adds 0. Allow +-4 counts of slack only.
    TEST_RESULT("DT-d Final position == sum of the two moves (dwell adds nothing)",
                llabs(dSeq - 2 * d1) <= 4);

    // -----------------------------------------------------------------------
    // Leave the device clean and at rest.
    // -----------------------------------------------------------------------
    uint8_t endFatal = readFatal(motor);
    printf("Fatal code before final reset = %d\n", endFatal);
    TEST_RESULT("DT No fatal error at end of module", endFatal == 0);

    cleanReset(motor);
}
