#include "tf_framework.h"

// ---------------------------------------------------------------------------
// tm_goto_edges.cpp
//
// Edge cases of the "Go to position" command (cmd 4) — an ABSOLUTE-target move.
//
// FIRMWARE GROUND TRUTH (firmware/Src/motor_control.c add_go_to_position_to_queue,
// firmware/Src/main.c GET_POSITION_COMMAND):
//   * Go to position is ABSOLUTE. The queued displacement is computed as
//       total_displacement = absolute_position - position_after_last_queue_item
//     i.e. relative to the planner's predicted END-of-queue position, NOT to the
//     live shaft. So it always drives the commanded profile to the SAME absolute
//     target regardless of what moves preceded it in the queue.
//   * It queues exactly 3 items (accel / coast / decel) via compute_trapezoid_move.
//   * "Get position" returns current_position_i96.position — the COMMANDED
//     (motion-profile) position, which lands on the requested target to within
//     the planner's integer rounding (the reference test test_go_to_position.py
//     asserts <=10 counts). So readback is deterministic and shaft-independent.
//   * A zero-displacement go-to-position (target == planner position) produces
//     acceleration 0 over the 3 segments: a valid no-op that stays put. (A zero
//     *duration* would be ERROR_PARAMETER_OUT_OF_RANGE (34) — not exercised here;
//     we always pass a nonzero duration.)
//
// This module probes four absolute-semantics edges (all gentle, <=0.25 rot,
// <=~0.5 rot/s, every sequence ending at rest):
//   (a) go-to-position to the CURRENT position (zero-distance no-op): accepted,
//       completes, stays within a tight tolerance.
//   (b) same absolute target commanded 3x: position does not drift after the
//       first (absolute semantics => repeats are no-ops).
//   (c) go-to-position queued BEHIND a trapezoid move: both execute in order and
//       the final commanded position equals the ABSOLUTE target, NOT the sum of
//       the relative trapezoid displacement and the target.
//   (d) the same physical point expressed in all four position units
//       (0.25 rot / 90 deg / pi/2 rad / 819200 counts) lands at the same place
//       (819200 = 0.25 * COUNTS_PER_REVOLUTION 3276800).
//
// Ends at commanded position 0, at rest, reset+drained.
//
// SAFETY:
//   * tfGetMotor() is unique-ID (extended) addressed: every command is
//     collision-safe on the 39-motor rack; no alias-88 or broadcast-response
//     frame is ever sent (systemReset is a no-response write). NO raw bus
//     injection.
//   * Open loop with MOSFETs enabled (readback is the commanded profile, so no
//     closed-loop transition is needed). All motion <= 0.25 rotation, peak speed
//     ~0.5 rot/s; every queued sequence ends at rest, so the queue can be
//     abandoned/reset at any point without a nonzero commanded velocity.
//   * No Test mode (cmd 36) values are ever sent.
//   * Every wait loop is bounded by a millis() timeout.
// ---------------------------------------------------------------------------

static const int   NORMAL_RESET_DELAY_MS = 1500;   // wait after a plain reset
static const int   ENABLE_SETTLE_MS      = 350;    // let the enable transient settle
static const float MOVE_DUR              = 1.0f;   // seconds per move (gentle)
static const float TARGET_ROT            = 0.25f;  // 0.25 rotation == 819200 counts
static const int32_t TARGET_COUNTS       = 819200; // 0.25 * 3276800 (AutoGeneratedUnitConversions.h)

// Tolerances in encoder counts. Readback is the commanded profile position, so
// error is only the planner's integer rounding (reference test uses 10 counts).
static const int64_t LAND_TOL   = 25;  // how close the commanded position lands to a target
static const int64_t STAY_TOL   = 8;   // no-op / no-drift: must barely move at all
static const int64_t AGREE_TOL  = 15;  // agreement between the four unit expressions

// pi/2 as the library receives a "radians" argument.
static const float QUARTER_TURN_RAD = 1.57079632679489661923f;

// Poll the motion queue until it drains to 0 (bounded by a wall-clock timeout),
// then a short settle. Returns the final observed depth (0xFF on comms failure).
static uint8_t waitForIdle(Servomotor* motor, uint32_t timeoutMs) {
    uint32_t start = millis();
    uint8_t n = 0xFF;
    while ((uint32_t)(millis() - start) < timeoutMs) {
        n = motor->getNQueuedItems();
        if (motor->getError() == 0 && n == 0) { delay(120); return 0; }
        delay(10);
    }
    return n;  // nonzero or 0xFF => timed out
}

// Latched fatal error code via Get status (answered normally even when latched).
// Returns 0xFF on a comms error so the caller can tell "no info" from "code 0".
static uint8_t readFatalErrorCode(Servomotor* motor) {
    getStatusResponse st = motor->getStatus();
    if (motor->getError() != 0) {
        printf("  (getStatus comms error: %d)\n", motor->getError());
        return 0xFF;
    }
    return st.fatalErrorCode;
}

// Read the commanded position in raw encoder counts (unit-setting independent).
static int64_t readPos(Servomotor* motor) {
    int64_t p = motor->getPositionRaw();
    if (motor->getError() != 0) {
        printf("  (getPositionRaw comms error: %d)\n", motor->getError());
    }
    return p;
}

static bool near64(int64_t a, int64_t b, int64_t tol) {
    int64_t d = a - b;
    if (d < 0) d = -d;
    return d <= tol;
}

void tm_goto_edges(void) {
    Serial.println("test_ard_goto_edges: BEGIN\n");

    Servomotor* motor = tfGetMotor();

    // ---- Clean, known starting state. ----
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);  // no response during reset; don't check errors

    uint8_t startFatal = readFatalErrorCode(motor);
    printf("Fatal code after reset: %d\n", startFatal);
    TEST_RESULT("GE No fatal error after reset", startFatal == 0);

    motor->setTimeUnit(TimeUnit::SECONDS);
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);

    motor->enableMosfets();
    checkMotorError(*motor, "enableMosfets");
    delay(ENABLE_SETTLE_MS);  // let the commutation-alignment transient settle

    // Zero AFTER enabling (never before): defines commanded position 0 cleanly.
    motor->zeroPosition();
    checkMotorError(*motor, "zeroPosition");
    delay(50);

    int64_t p0 = readPos(motor);
    printf("Commanded position after zero: %lld (expect ~0)\n", (long long)p0);
    TEST_RESULT("GE Commanded position is 0 after zeroPosition", near64(p0, 0, STAY_TOL));

    // =======================================================================
    // (a) Go-to-position to the CURRENT position: zero-distance no-op.
    //     Move to the target, then command the SAME absolute counts value again;
    //     the firmware computes displacement 0 and must stay put.
    // =======================================================================
    printf("\n--- (a) zero-distance no-op ---\n");

    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    motor->goToPosition(TARGET_ROT, MOVE_DUR);
    checkMotorError(*motor, "goToPosition(a warmup)");
    uint8_t da = waitForIdle(motor, 8000);
    int64_t posA1 = readPos(motor);
    printf("At target: queueDrained=%d pos=%lld (expect ~%d)\n",
           (int)(da == 0), (long long)posA1, TARGET_COUNTS);
    TEST_RESULT("GE-a Warmup move drained the queue", da == 0);
    TEST_RESULT("GE-a Warmup landed at target", near64(posA1, TARGET_COUNTS, LAND_TOL));

    // Command go-to-position to the exact current commanded counts (displacement 0).
    motor->setPositionUnit(PositionUnit::ENCODER_COUNTS);
    motor->goToPositionRaw((int32_t)posA1, (uint32_t)(MOVE_DUR * CONVERSION_FACTOR_SECONDS));
    bool aComms = (motor->getError() == 0);
    uint8_t da2 = waitForIdle(motor, 6000);
    uint8_t aFatal = readFatalErrorCode(motor);
    int64_t posA2 = readPos(motor);
    printf("No-op: comms=%d fatal=%d drained=%d pos=%lld (was %lld)\n",
           (int)aComms, (int)aFatal, (int)(da2 == 0), (long long)posA2, (long long)posA1);
    TEST_RESULT("GE-a No-op go-to-position accepted (comms ok, no fatal)",
                aComms && aFatal == 0);        // error_codes.json: 0 == ERROR_NONE
    TEST_RESULT("GE-a No-op go-to-position completes (queue drains)", da2 == 0);
    TEST_RESULT("GE-a No-op go-to-position stays put", near64(posA2, posA1, STAY_TOL));

    // =======================================================================
    // (b) Same absolute target commanded 3x: no drift after the first.
    // =======================================================================
    printf("\n--- (b) repeat same absolute target 3x ---\n");

    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    int64_t reps[3] = {0, 0, 0};
    bool repsComms = true;
    for (int i = 0; i < 3; i++) {
        motor->goToPosition(TARGET_ROT, MOVE_DUR);
        if (motor->getError() != 0) repsComms = false;
        uint8_t d = waitForIdle(motor, 8000);
        if (d != 0) printf("  repeat %d: queue did not drain (%d)\n", i, (int)d);
        reps[i] = readPos(motor);
        printf("  repeat %d: pos=%lld\n", i, (long long)reps[i]);
    }
    uint8_t bFatal = readFatalErrorCode(motor);
    TEST_RESULT("GE-b Repeats accepted (comms ok, no fatal)", repsComms && bFatal == 0);
    TEST_RESULT("GE-b 2nd repeat did not drift from 1st", near64(reps[1], reps[0], STAY_TOL));
    TEST_RESULT("GE-b 3rd repeat did not drift from 1st", near64(reps[2], reps[0], STAY_TOL));
    TEST_RESULT("GE-b Repeats stayed at the absolute target",
                near64(reps[2], TARGET_COUNTS, LAND_TOL));

    // Return to 0 for the next section.
    motor->goToPosition(0.0f, MOVE_DUR);
    checkMotorError(*motor, "goToPosition(0 before c)");
    waitForIdle(motor, 8000);

    // =======================================================================
    // (c) Go-to-position queued BEHIND a trapezoid move.
    //     From commanded 0: trapezoid +0.20 rot (RELATIVE), then go-to 0.25 rot
    //     (ABSOLUTE) queued behind it WITHOUT waiting. Absolute must win:
    //       final == 0.25 rot (819200), NOT 0.20 + 0.25 = 0.45 rot (1474560).
    // =======================================================================
    printf("\n--- (c) go-to-position queued behind a trapezoid move ---\n");

    int64_t preC = readPos(motor);
    printf("Commanded position before (c): %lld (expect ~0)\n", (long long)preC);

    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    motor->trapezoidMove(0.20f, MOVE_DUR);            // RELATIVE +0.20 rot
    bool cComms1 = (motor->getError() == 0);
    motor->goToPosition(TARGET_ROT, MOVE_DUR);        // ABSOLUTE 0.25 rot, queued behind
    bool cComms2 = (motor->getError() == 0);

    uint8_t nQueuedC = motor->getNQueuedItems();      // both moves should be queued (up to 6 items)
    printf("Queued items after both sends: %d\n", (int)nQueuedC);
    TEST_RESULT("GE-c Both moves accepted at the comms layer", cComms1 && cComms2);
    TEST_RESULT("GE-c Trapezoid + go-to both queued (depth > 0)",
                motor->getError() == 0 && nQueuedC > 0);

    uint8_t dc = waitForIdle(motor, 12000);
    uint8_t cFatal = readFatalErrorCode(motor);
    int64_t posC = readPos(motor);
    printf("After both executed: drained=%d fatal=%d pos=%lld (absolute target %d, "
           "relative-sum would be %d)\n",
           (int)(dc == 0), (int)cFatal, (long long)posC, TARGET_COUNTS, 1474560);
    TEST_RESULT("GE-c Sequence completed without fatal error", dc == 0 && cFatal == 0);
    TEST_RESULT("GE-c Final position is the ABSOLUTE target (not the relative sum)",
                near64(posC, TARGET_COUNTS, LAND_TOL));

    // =======================================================================
    // (d) Same physical point in all four position units lands together.
    //     Each command is absolute, so after the first the rest are near-no-ops;
    //     we assert every unit lands at 819200 counts and they agree with (a)/(b).
    // =======================================================================
    printf("\n--- (d) four unit expressions of the same physical point ---\n");

    struct UnitCase { PositionUnit unit; float value; const char* label; };
    const UnitCase CASES[4] = {
        { PositionUnit::SHAFT_ROTATIONS, TARGET_ROT,          "0.25 rot"       },
        { PositionUnit::DEGREES,         90.0f,               "90 deg"         },
        { PositionUnit::RADIANS,         QUARTER_TURN_RAD,             "pi/2 rad"       },
        { PositionUnit::ENCODER_COUNTS,  (float)TARGET_COUNTS,"819200 counts"  },
    };

    int64_t landed[4] = {0, 0, 0, 0};
    bool dComms = true;
    uint8_t dFatal = 0;
    for (int i = 0; i < 4; i++) {
        motor->setPositionUnit(CASES[i].unit);
        motor->goToPosition(CASES[i].value, MOVE_DUR);
        if (motor->getError() != 0) dComms = false;
        uint8_t d = waitForIdle(motor, 8000);
        if (d != 0) printf("  %s: queue did not drain (%d)\n", CASES[i].label, (int)d);
        landed[i] = readPos(motor);
        printf("  %-14s -> pos=%lld (expect ~%d)\n",
               CASES[i].label, (long long)landed[i], TARGET_COUNTS);
    }
    dFatal = readFatalErrorCode(motor);
    TEST_RESULT("GE-d All four unit moves accepted (comms ok, no fatal)",
                dComms && dFatal == 0);

    bool allLand = true;
    for (int i = 0; i < 4; i++)
        if (!near64(landed[i], TARGET_COUNTS, LAND_TOL)) allLand = false;
    TEST_RESULT("GE-d All four units land at the physical point (819200 counts)", allLand);

    int64_t lo = landed[0], hi = landed[0];
    for (int i = 1; i < 4; i++) {
        if (landed[i] < lo) lo = landed[i];
        if (landed[i] > hi) hi = landed[i];
    }
    printf("  spread across units: %lld counts\n", (long long)(hi - lo));
    TEST_RESULT("GE-d Four unit expressions agree with each other",
                (hi - lo) <= AGREE_TOL);

    // ---- Leave the device clean: back to 0, at rest, reset. ----
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    motor->goToPosition(0.0f, MOVE_DUR);
    waitForIdle(motor, 8000);
    motor->disableMosfets();
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);
    // drain any late bytes
    // (host harness drains between modules too; this is belt-and-suspenders)
}
