#include "tf_framework.h"

// ---------------------------------------------------------------------------
// tm_homing_edges.cpp
//
// Edge-case probe for the HOMING command (cmd 30) preconditions and boundaries.
// Every assertion encodes firmware GROUND TRUTH, verified in:
//   - firmware/Src/motor_control.c  start_homing()               (lines ~1387)
//   - firmware/Src/motor_control.c  add_trapezoid_move_to_queue()(lines ~1938)
//   - firmware/Src/main.c           HOMING_COMMAND dispatch      (lines ~428)
//   - python_programs/servomotor/error_codes.json                (codes 13, 34)
//
// The firmware homing entry point (start_homing) runs these checks IN ORDER:
//   1. if(motor_control_mode != CLOSED_LOOP_POSITION_CONTROL)
//          fatal_error(ERROR_NOT_IN_CLOSED_LOOP);        // code 13
//   2. if(n_items_in_queue != 0) fatal_error(ERROR_QUEUE_NOT_EMPTY); // code 8
//   3. add_trapezoid_move_to_queue(displacement, time)
//          -> if(total_time == 0) fatal_error(ERROR_PARAMETER_OUT_OF_RANGE); // code 34
// After boot / System reset the device is in OPEN_LOOP_POSITION_CONTROL
// (motor_control.c line 170: static uint8_t motor_control_mode =
// OPEN_LOOP_POSITION_CONTROL), so a bare Homing latches fatal 13.
//
// These fatal_error() paths LATCH the device in the fatal-error state exactly
// like the error-injection module: only Get status and System reset are
// answered normally, and System reset clears it. So each rejection is verified
// by reading the latched code via Get status, then recovered with System reset.
//
// THREE CASES (per spec, adjusted to firmware ground truth):
//   (a) Homing WITHOUT closed loop -> firmware ground truth is a LATCHED FATAL
//       error, code 13 (ERROR_NOT_IN_CLOSED_LOOP) -- NOT a soft rejection. The
//       spec left "rejection code or acceptance" open; firmware says fatal 13.
//   (b) Homing with zero maxDuration (in closed loop, empty queue) -> fatal 34
//       (ERROR_PARAMETER_OUT_OF_RANGE), from the total_time==0 guard in
//       add_trapezoid_move_to_queue. Reached only AFTER the closed-loop check
//       passes, so this case first enters closed loop.
//   (c) Homing a tiny distance (0.02 rot) in closed loop on a FREE shaft:
//       no obstacle -> handle_homing_logic never trips its 50000-count collision
//       threshold, the trapezoid runs to completion, the queue drains, and the
//       commanded position ends ~0.02 rot from where homing started, at rest.
//
// SAFETY:
//   * tfGetMotor() is unique-ID (extended) addressed: every command is
//     collision-safe on the 39-motor rack; nothing is broadcast that solicits
//     multi-device responses.
//   * The only motion is the single 0.02-rotation homing move of case (c)
//     (<= 1 rot, peak velocity ~0.08 rot/s << 3 rot/s), which is a trapezoid
//     that ends at REST by construction.
//   * No test-mode (cmd 36) values are ever sent (no 10..13 hang risk).
//   * After each deliberately-induced fatal error: systemReset + 1500 ms +
//     drain before proceeding.
//   * No raw bus frames are written; only library methods are used.
// ---------------------------------------------------------------------------

static const int NORMAL_RESET_DELAY_MS = 1500;  // wait after a plain reset
static const int FATAL_RESET_DELAY_MS  = 2000;  // wait after recovering a fatal error
static const int SETTLE_MS             = 350;   // commutation-alignment settle after closed loop
static const int INJECT_SETTLE_MS      = 300;   // let a rejection latch before reading status

// Firmware error codes (verified in python_programs/servomotor/error_codes.json).
static const uint8_t ERROR_NOT_IN_CLOSED_LOOP    = 13; // start_homing check #1
static const uint8_t ERROR_PARAMETER_OUT_OF_RANGE = 34; // add_trapezoid_move_to_queue total_time==0

// Position scale (AutoGeneratedUnitConversions.h COUNTS_PER_REVOLUTION 3276800).
static const double COUNTS_PER_ROT = 3276800.0;
static const float  TINY_ROT       = 0.02f;   // case (c) homing displacement
static const float  HOMING_DUR_S   = 0.5f;    // case (c) max homing time (gentle)

// Read the latched fatal error code via Get status (answered even while latched).
// Returns 0xFF on a comms-layer failure so callers can tell "no info" from code 0.
static uint8_t readFatalErrorCode(Servomotor* motor) {
    getStatusResponse st = motor->getStatus();
    if (motor->getError() != 0) {
        printf("  (getStatus comms error: %d)\n", motor->getError());
        return 0xFF;
    }
    return st.fatalErrorCode;
}

// Read the current motion-queue depth; returns 0xFF on a comms error.
static uint8_t readQueueDepth(Servomotor* motor) {
    uint8_t n = motor->getNQueuedItems();
    if (motor->getError() != 0) {
        printf("  (getNQueuedItems comms error: %d)\n", motor->getError());
        return 0xFF;
    }
    return n;
}

// Poll the queue until it drains to empty (bounded), then settle. Returns the
// last depth read (0 on success, 0xFF if it never drained / comms failed).
static uint8_t waitForIdle(Servomotor* motor, uint32_t timeoutMs) {
    uint8_t n = 0xFF;
    uint32_t start = millis();
    while (millis() - start < timeoutMs) {
        n = motor->getNQueuedItems();
        if (motor->getError() == 0 && n == 0) break;
        delay(10);
    }
    delay(150);  // settle margin
    return n;
}

// Bring the device to a clean, known, open-loop state and confirm no fatal.
static void resetClean(Servomotor* motor, int delayMs) {
    motor->systemReset();
    delay(delayMs);  // no response during reset; don't check errors
    // Drain any straggler bytes on the host serial port.
    for (uint32_t tf_drain_t0 = millis(); Serial1.available() && (millis() - tf_drain_t0) < 500; ) Serial1.read();  // bounded drain (hang-proof)
}

void tm_homing_edges(void) {
    Serial.println("test_ard_homing_edges: BEGIN\n");

    Servomotor* motor = tfGetMotor();

    // ---- Clean, known starting state (open loop after reset). ----
    resetClean(motor, NORMAL_RESET_DELAY_MS);
    motor->setTimeUnit(TimeUnit::SECONDS);
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);

    uint8_t startFatal = readFatalErrorCode(motor);
    printf("Fatal error code after initial reset: %d (expect 0)\n", startFatal);
    TEST_RESULT("HE No fatal error after initial reset", startFatal == 0);

    // =======================================================================
    // CASE (a): Homing WITHOUT closed loop.
    // After reset the device is in OPEN_LOOP_POSITION_CONTROL, so start_homing's
    // first check (motor_control.c ~line 1389-1390) raises
    // fatal_error(ERROR_NOT_IN_CLOSED_LOOP) == 13. Use a NONZERO duration so the
    // zero-duration guard cannot fire first: the closed-loop check is what trips.
    // =======================================================================
    printf("\n--- CASE (a): Homing with no closed loop -> expect fatal 13 ---\n");

    // homingRaw(distance_counts, duration_timesteps): 15625 * 32us = 0.5 s (nonzero).
    motor->homingRaw((int32_t)(TINY_ROT * COUNTS_PER_ROT), 15625);
    delay(INJECT_SETTLE_MS);

    uint8_t codeA = readFatalErrorCode(motor);
    printf("  latched fatal code = %d (expect %d = ERROR_NOT_IN_CLOSED_LOOP)\n",
           codeA, ERROR_NOT_IN_CLOSED_LOOP);
    // Ground truth: firmware/Src/motor_control.c start_homing() ->
    // fatal_error(ERROR_NOT_IN_CLOSED_LOOP); error_codes.json code 13.
    TEST_RESULT("HE (a) Homing without closed loop latches fatal 13",
                codeA == ERROR_NOT_IN_CLOSED_LOOP);

    // Recover.
    resetClean(motor, FATAL_RESET_DELAY_MS);
    uint8_t recA = readFatalErrorCode(motor);
    printf("  after recovery reset: fatal code = %d (expect 0)\n", recA);
    TEST_RESULT("HE (a) Recovered after reset", recA == 0);

    // =======================================================================
    // CASE (b): Homing with zero maxDuration, IN closed loop, empty queue.
    // The closed-loop and queue checks pass, then add_trapezoid_move_to_queue()
    // hits its total_time==0 guard (motor_control.c ~line 1944-1945) ->
    // fatal_error(ERROR_PARAMETER_OUT_OF_RANGE) == 34.
    // =======================================================================
    printf("\n--- CASE (b): Homing with zero maxDuration -> expect fatal 34 ---\n");

    motor->goToClosedLoop();  // M17: enables MOSFETs + switches to closed loop
    checkMotorError(*motor, "goToClosedLoop (b)");
    delay(SETTLE_MS);         // commutation-alignment settle

    uint8_t clFatalB = readFatalErrorCode(motor);
    printf("  fatal after goToClosedLoop = %d (expect 0)\n", clFatalB);
    TEST_RESULT("HE (b) No fatal after entering closed loop", clFatalB == 0);

    uint8_t qB = readQueueDepth(motor);
    printf("  queue depth before homing = %d (expect 0)\n", qB);
    // Precondition: an empty queue guarantees the zero-duration guard (not the
    // queue-not-empty guard, code 8) is what the homing hits.
    TEST_RESULT("HE (b) Queue empty before zero-duration homing", qB == 0);

    // homingRaw with duration EXACTLY 0 timesteps: deterministic zero-parameter path.
    motor->homingRaw((int32_t)(TINY_ROT * COUNTS_PER_ROT), 0);
    delay(INJECT_SETTLE_MS);

    uint8_t codeB = readFatalErrorCode(motor);
    printf("  latched fatal code = %d (expect %d = ERROR_PARAMETER_OUT_OF_RANGE)\n",
           codeB, ERROR_PARAMETER_OUT_OF_RANGE);
    // Ground truth: firmware/Src/motor_control.c add_trapezoid_move_to_queue()
    // total_time==0 -> fatal_error(ERROR_PARAMETER_OUT_OF_RANGE); code 34.
    TEST_RESULT("HE (b) Zero-duration homing latches fatal 34",
                codeB == ERROR_PARAMETER_OUT_OF_RANGE);

    // Recover.
    resetClean(motor, FATAL_RESET_DELAY_MS);
    uint8_t recB = readFatalErrorCode(motor);
    printf("  after recovery reset: fatal code = %d (expect 0)\n", recB);
    TEST_RESULT("HE (b) Recovered after reset", recB == 0);

    // =======================================================================
    // CASE (c): Tiny homing (0.02 rot) in closed loop on a FREE shaft.
    // No obstacle -> no collision trip (handle_homing_logic 50000-count
    // threshold, motor_control.c ~line 1413), the trapezoid runs to completion,
    // the queue drains, motor_busy clears, and the commanded position ends
    // ~0.02 rot from the start, at rest with no fatal error.
    // =======================================================================
    printf("\n--- CASE (c): Tiny 0.02-rot homing completes on free shaft ---\n");

    // Units already SECONDS / SHAFT_ROTATIONS; re-assert (state is per-object).
    motor->setTimeUnit(TimeUnit::SECONDS);
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);

    motor->goToClosedLoop();
    checkMotorError(*motor, "goToClosedLoop (c)");
    delay(SETTLE_MS);

    uint8_t clFatalC = readFatalErrorCode(motor);
    printf("  fatal after goToClosedLoop = %d (expect 0)\n", clFatalC);
    TEST_RESULT("HE (c) No fatal after entering closed loop", clFatalC == 0);

    int64_t startPos = motor->getPositionRaw();
    bool startPosOk = (motor->getError() == 0);
    printf("  start commanded position (raw counts) = %lld (commsOk=%d)\n",
           (long long)startPos, (int)startPosOk);

    // Command the tiny homing move (float overload exercises unit conversion).
    motor->homing(TINY_ROT, HOMING_DUR_S);
    if (motor->getError() != 0) {
        printf("  homing() comms error: %d\n", motor->getError());
    }

    // Wait for the homing trapezoid to complete and the queue to drain.
    uint8_t drained = waitForIdle(motor, 5000);
    printf("  queue depth after homing = %d (expect 0 = completed, at rest)\n", drained);
    TEST_RESULT("HE (c) Homing completes: queue drains to zero (at rest)", drained == 0);

    // No fatal error may have latched (no collision, no run-out-of-queue-items).
    uint8_t codeC = readFatalErrorCode(motor);
    printf("  fatal code after homing = %d (expect 0)\n", codeC);
    TEST_RESULT("HE (c) Tiny homing completed with no fatal error", codeC == 0);

    // Commanded position must have advanced ~0.02 rot from the start.
    int64_t endPos = motor->getPositionRaw();
    bool endPosOk = (motor->getError() == 0);
    double deltaCounts = (double)(endPos - startPos);
    double expectedCounts = (double)TINY_ROT * COUNTS_PER_ROT;  // 0.02 * 3276800 = 65536
    printf("  end position (raw) = %lld  delta = %.0f counts (expect ~%.0f)\n",
           (long long)endPos, deltaCounts, expectedCounts);
    // Generous tolerance (~0.005 rot = 16384 counts): distinguishes a real 0.02-rot
    // move from no motion while tolerating any small closed-loop tracking offset.
    bool posOk = startPosOk && endPosOk &&
                 approxEqual((float)deltaCounts, (float)expectedCounts, 16384.0f);
    TEST_RESULT("HE (c) Ends ~0.02 rot from start (within 0.005 rot)", posOk);

    // ---- Leave the device clean and at rest. ----
    resetClean(motor, NORMAL_RESET_DELAY_MS);
    uint8_t finalFatal = readFatalErrorCode(motor);
    printf("\nFinal fatal code = %d (expect 0)\n", finalFatal);
    TEST_RESULT("HE Clean at end (no fatal error)", finalFatal == 0);
}
