#include "tf_framework.h"

// ---------------------------------------------------------------------------
// tm_position_frames.cpp
//
// Position reference-frame edge cases on a closed-loop, calibrated motor.
// Probes the int64 signed-position path, zeroPosition re-basing, sign
// preservation across unit conversion, and the firmware's actual guard on
// zeroPosition. Every asserted number is firmware/ground-truth verified.
//
// GROUND TRUTH used here:
//   * Internal position unit = encoder counts.
//       CONVERSION_FACTOR_SHAFT_ROTATIONS = 3276800 counts / rotation
//       CONVERSION_FACTOR_DEGREES         = 9102.2222 counts / degree
//     (Arduino_library/AutoGeneratedUnitConversions.h). Therefore
//     -0.5 rotation == -180 degrees == -1638400 counts EXACTLY (both fit in
//     float without loss, |x| < 2^24), so the two representations must agree.
//   * getPosition / get_motor_position return the int64 commanded position
//     (firmware/Src/motor_control.c get_motor_position -> current_position_i96,
//     main.c GET_POSITION_COMMAND). goToPosition is ABSOLUTE; a -0.5 rot target
//     from zero must land at a NEGATIVE raw count (signed int64 path).
//   * zero_position() (motor_control.c:3229) guards ONLY on a non-empty queue:
//       if (n_items_in_queue != 0) fatal_error(ERROR_QUEUE_NOT_EMPTY);
//     It then zeroes commanded position, hall position, velocity and PID state.
//     It does NOT check MOSFET/closed-loop state. So:
//       (b) each zeroPosition re-bases the frame to ~0 (commanded AND hall);
//       (d) zeroPosition with MOSFETs DISABLED (queue empty) is ALLOWED -- no
//           fatal error. (This contradicts the naive guess that it would be
//           rejected; firmware is the authority. See SPEC note (d) below.)
//   * ERROR_QUEUE_NOT_EMPTY == 8  (python_programs/servomotor/error_codes.json).
//     A zeroPosition issued while a move is still queued must latch fatal 8;
//     only Get status / System reset answer normally in that latched state
//     (see tm_error_injection.cpp), and System reset clears it.
//   * Status flag bits (common_source_files/device_status.h):
//       STATUS_MOSFETS_ENABLED_FLAG_BIT = 1 (0x02)
//       STATUS_CLOSED_LOOP_FLAG_BIT     = 2 (0x04)
//
// SPEC note (d): the spec sketch asked "zeroPosition while MOSFETs disabled:
// allowed?" -- firmware says YES (queue-empty is the only precondition), so the
// test asserts NO fatal error. Followed the firmware, not a guess.
//
// SAFETY:
//   * All motion is closed-loop absolute moves of <= 0.5 rotation over >= 1.0 s
//     (peak ~1 rot/s, well under 3 rot/s), each ending at rest; queue is fully
//     drained before every position assert and before every zeroPosition.
//   * The one deliberately-induced fatal error (queue-not-empty guard) is
//     followed immediately by systemReset + delay(1500) + drain before anything
//     else, and no command other than Get status is sent while latched.
//   * NO test-mode (cmd 36) values are used anywhere (no 10..13 hang risk).
//   * tfGetMotor() is unique-ID (extended) addressed, so every frame is
//     collision-safe on the 39-motor rack; nothing is broadcast. No raw bus
//     injection.
//   * While MOSFETs are disabled we command NO motion (only zero + reads), so
//     no commanded-vs-shaft deviation can accumulate.
// ---------------------------------------------------------------------------

static const int NORMAL_RESET_DELAY_MS = 1500;  // wait after a plain reset
static const int CLOSED_LOOP_SETTLE_MS = 600;   // let closed-loop engagement settle
static const int MOVE_SETTLE_MS        = 250;   // settle after a drained move

static const uint8_t ERROR_QUEUE_NOT_EMPTY = 8; // error_codes.json

// counts per unit (AutoGeneratedUnitConversions.h)
static const float COUNTS_PER_ROT = 3276800.0f;

// Tolerances (encoder counts). 0.03 rot ~= 98304 counts -- generous vs hall
// noise / closed-loop hold jitter, tight enough to catch sign or scale bugs.
static const float NEAR_ZERO_TOL_ROT = 0.03f;   // "reads ~0"
static const float LAND_TOL_ROT      = 0.05f;   // landed-at-target accuracy
static const float LAND_TOL_DEG      = 5.0f;    // landed-at-target accuracy (deg)
static const float CLEAR_NEG_ROT     = -0.10f;  // "clearly negative" threshold

// Drain the motion queue to empty (bounded), then settle. Returns final depth
// (0xFF on comms error). NEVER call while a fatal error is latched.
static uint8_t drainQueue(Servomotor* motor, uint32_t timeoutMs) {
    uint8_t n = 0xFF;
    uint32_t start = millis();
    while (millis() - start < timeoutMs) {
        n = motor->getNQueuedItems();
        if (motor->getError() == 0 && n == 0) break;
        delay(10);
    }
    delay(MOVE_SETTLE_MS);
    return n;
}

// Read the latched fatal error code via Get status (answered even when latched).
// Returns 0xFF on comms error so the caller can tell "no info" from "code 0".
static uint8_t readFatalCode(Servomotor* motor) {
    getStatusResponse st = motor->getStatus();
    if (motor->getError() != 0) {
        printf("  (getStatus comms error: %d)\n", motor->getError());
        return 0xFF;
    }
    return st.fatalErrorCode;
}

// Bring the (calibrated) motor into closed loop and re-base to zero cleanly.
// Leaves MOSFETs on, closed loop active, commanded position ~0.
static void engageClosedLoopAndZero(Servomotor* motor) {
    motor->setTimeUnit(TimeUnit::SECONDS);
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    motor->goToClosedLoop();          // enables MOSFETs + enters closed loop (gentle)
    checkMotorError(*motor, "goToClosedLoop");
    delay(CLOSED_LOOP_SETTLE_MS);     // settle the engagement transient before zero
    motor->zeroPosition();            // queue empty here -> no ERROR_QUEUE_NOT_EMPTY
    checkMotorError(*motor, "zeroPosition(initial)");
    delay(MOVE_SETTLE_MS);
}

void tm_position_frames(void) {
    Serial.println("test_ard_position_frames: BEGIN\n");

    Servomotor* motor = tfGetMotor();

    // ----------------------------------------------------------------------
    // Clean, known starting state.
    // ----------------------------------------------------------------------
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);
    for (uint32_t tf_drain_t0 = millis(); Serial1.available() && (millis() - tf_drain_t0) < 500; ) Serial1.read();  // bounded drain (hang-proof)

    uint8_t startFatal = readFatalCode(motor);
    printf("Fatal code after reset: %d\n", startFatal);
    TEST_RESULT("PF No fatal error after initial reset", startFatal == 0);

    engageClosedLoopAndZero(motor);

    // Confirm we really are in closed loop with MOSFETs on (status flag bits).
    getStatusResponse clStatus = motor->getStatus();
    bool clOk = (motor->getError() == 0);
    printf("After goToClosedLoop: flags=0x%04X\n",
           clOk ? (unsigned)clStatus.statusFlags : 0xFFFFu);
    // bit1=MOSFETs enabled (0x02), bit2=closed loop (0x04)  (device_status.h)
    TEST_RESULT("PF MOSFETs enabled + closed loop after goToClosedLoop",
                clOk && (clStatus.statusFlags & 0x02) && (clStatus.statusFlags & 0x04));

    // Baseline: after the initial zero, commanded position reads ~0.
    int64_t zeroRaw = motor->getPositionRaw();
    printf("Raw counts after initial zero: %lld\n", (long long)zeroRaw);
    TEST_RESULT("PF Position ~0 after initial zero",
                approxEqual((float)zeroRaw / COUNTS_PER_ROT, 0.0f, NEAR_ZERO_TOL_ROT));

    // =======================================================================
    // (a) NEGATIVE absolute position: goToPosition(-0.5 rot) lands at -0.5,
    //     raw counts NEGATIVE (signed int64 path), comprehensive agrees.
    // =======================================================================
    printf("\n--- (a) negative absolute position: goToPosition(-0.5 rot) ---\n");
    motor->goToPosition(-0.5f, 1.0f);       // absolute target -0.5 rot over 1.0 s
    checkMotorError(*motor, "goToPosition(-0.5)");
    uint8_t dA = drainQueue(motor, 8000);
    printf("Queue after -0.5 move: %d (expect 0)\n", dA);
    TEST_RESULT("PF-a Queue drained after -0.5 move", dA == 0);

    int64_t negRaw = motor->getPositionRaw();
    float   negRot = motor->getPosition();  // still SHAFT_ROTATIONS
    printf("At -0.5 target: raw=%lld  getPosition=%.4f rot\n",
           (long long)negRaw, negRot);
    // Signed int64 path: a negative absolute target must produce negative counts.
    TEST_RESULT("PF-a Raw position is negative (int64 signed path)",
                (float)negRaw / COUNTS_PER_ROT < CLEAR_NEG_ROT);
    TEST_RESULT("PF-a getPosition lands ~-0.5 rot",
                approxEqual(negRot, -0.5f, LAND_TOL_ROT));

    // Comprehensive position must agree in negative territory (commanded & hall).
    getComprehensivePositionResponseConverted comp = motor->getComprehensivePosition();
    bool compOk = (motor->getError() == 0);
    printf("Comprehensive: commanded=%.4f hall=%.4f (rot)\n",
           comp.commandedPosition, comp.hallSensorPosition);
    TEST_RESULT("PF-a Comprehensive commanded ~-0.5 rot",
                compOk && approxEqual(comp.commandedPosition, -0.5f, LAND_TOL_ROT));
    TEST_RESULT("PF-a Comprehensive hall is negative (agrees in - territory)",
                compOk && comp.hallSensorPosition < CLEAR_NEG_ROT);

    // Return to zero for the next stage.
    motor->goToPosition(0.0f, 1.0f);
    checkMotorError(*motor, "goToPosition(0)");
    drainQueue(motor, 8000);

    // =======================================================================
    // (b) Sequential zeroPosition re-bases: move to 0.3, zero, move to 0.3,
    //     zero again -- each zero drives commanded AND hall back to ~0.
    // =======================================================================
    printf("\n--- (b) sequential zeroPosition re-basing ---\n");
    for (int pass = 1; pass <= 2; pass++) {
        char name[96];

        motor->goToPosition(0.3f, 1.0f);    // absolute 0.3 rot
        checkMotorError(*motor, "goToPosition(0.3)");
        uint8_t d = drainQueue(motor, 8000);

        float atTarget = motor->getPosition();
        printf("  pass %d: at 0.3 target, getPosition=%.4f rot (queue=%d)\n",
               pass, atTarget, d);
        snprintf(name, sizeof(name), "PF-b Pass %d reached ~0.3 rot before zero", pass);
        TEST_RESULT(name, d == 0 && approxEqual(atTarget, 0.3f, LAND_TOL_ROT));

        // Queue is drained, so zeroPosition is accepted (no ERROR_QUEUE_NOT_EMPTY).
        motor->zeroPosition();
        checkMotorError(*motor, "zeroPosition(sequential)");
        delay(MOVE_SETTLE_MS);

        uint8_t f = readFatalCode(motor);
        snprintf(name, sizeof(name), "PF-b Pass %d zeroPosition raised no fatal error", pass);
        TEST_RESULT(name, f == 0);

        float afterZero = motor->getPosition();
        float hallAfter = motor->getHallSensorPosition();
        printf("  pass %d: after zero, commanded=%.4f hall=%.4f rot\n",
               pass, afterZero, hallAfter);
        snprintf(name, sizeof(name), "PF-b Pass %d commanded re-based to ~0", pass);
        TEST_RESULT(name, approxEqual(afterZero, 0.0f, NEAR_ZERO_TOL_ROT));
        snprintf(name, sizeof(name), "PF-b Pass %d hall re-based to ~0", pass);
        TEST_RESULT(name, approxEqual(hallAfter, 0.0f, NEAR_ZERO_TOL_ROT));
    }

    // =======================================================================
    // (c) DEGREES unit: goToPosition(-180 deg) returns ~-180 (sign preserved
    //     across the unit conversion), and cross-checks to -0.5 rot / negative
    //     raw counts (-180 deg == -0.5 rot == -1638400 counts exactly).
    // =======================================================================
    printf("\n--- (c) degrees: goToPosition(-180 deg), sign preserved ---\n");
    motor->setPositionUnit(PositionUnit::DEGREES);
    motor->goToPosition(-180.0f, 1.0f);     // -180 deg absolute (== -0.5 rot)
    checkMotorError(*motor, "goToPosition(-180 deg)");
    uint8_t dC = drainQueue(motor, 8000);

    float negDeg = motor->getPosition();    // DEGREES
    int64_t negDegRaw = motor->getPositionRaw();
    printf("At -180 deg target: getPosition=%.3f deg  raw=%lld\n",
           negDeg, (long long)negDegRaw);
    TEST_RESULT("PF-c Queue drained after -180 deg move", dC == 0);
    TEST_RESULT("PF-c getPosition returns ~-180 deg (sign preserved)",
                approxEqual(negDeg, -180.0f, LAND_TOL_DEG));
    TEST_RESULT("PF-c Raw is negative at -180 deg (int64 signed path)",
                (float)negDegRaw / COUNTS_PER_ROT < CLEAR_NEG_ROT);

    // Same physical position read in ROTATIONS must be ~-0.5 (unit-agnostic sign).
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    float sameInRot = motor->getPosition();
    printf("Same position in rotations: %.4f rot (expect ~-0.5)\n", sameInRot);
    TEST_RESULT("PF-c -180 deg equals ~-0.5 rot (cross-unit agreement)",
                approxEqual(sameInRot, -0.5f, LAND_TOL_ROT));

    // Return to zero and drain before the fatal-guard probe.
    motor->goToPosition(0.0f, 1.0f);
    checkMotorError(*motor, "goToPosition(0) after deg");
    drainQueue(motor, 8000);

    // =======================================================================
    // (e) zeroPosition GUARD: issued while a move is still queued must latch
    //     ERROR_QUEUE_NOT_EMPTY (8). Verify, then recover with System reset.
    //     (Firmware: zero_position() -> fatal_error(ERROR_QUEUE_NOT_EMPTY).)
    // =======================================================================
    printf("\n--- (e) zeroPosition while queue NOT empty -> fatal 8 ---\n");
    motor->goToPosition(0.2f, 2.0f);        // slow move: still in queue when we zero
    checkMotorError(*motor, "goToPosition(0.2) slow");
    // Do NOT drain: the move is executing, so the queue is non-empty.
    motor->zeroPosition();                  // expected to latch ERROR_QUEUE_NOT_EMPTY
    delay(150);                             // let the fatal state latch

    uint8_t guardFatal = readFatalCode(motor);
    printf("Fatal code after zero-with-queue: %d (expect %d)\n",
           guardFatal, ERROR_QUEUE_NOT_EMPTY);
    TEST_RESULT("PF-e zeroPosition on non-empty queue latches ERROR_QUEUE_NOT_EMPTY (8)",
                guardFatal == ERROR_QUEUE_NOT_EMPTY);

    // Recover fully before continuing (only reset/get-status valid while latched).
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);
    for (uint32_t tf_drain_t0 = millis(); Serial1.available() && (millis() - tf_drain_t0) < 500; ) Serial1.read();  // bounded drain (hang-proof)
    uint8_t afterGuardReset = readFatalCode(motor);
    TEST_RESULT("PF-e System reset clears the queue-not-empty fatal", afterGuardReset == 0);

    // =======================================================================
    // (d) zeroPosition with MOSFETs DISABLED (queue empty) is ALLOWED. The
    //     firmware guard is queue-empty only; MOSFET state is irrelevant.
    //     After the reset above, MOSFETs are off and the queue is empty.
    // =======================================================================
    printf("\n--- (d) zeroPosition with MOSFETs disabled (queue empty) ---\n");
    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    motor->disableMosfets();                // explicit: ensure MOSFETs are OFF
    checkMotorError(*motor, "disableMosfets");
    delay(200);

    uint8_t preZeroDepth = motor->getNQueuedItems();
    bool depthOk = (motor->getError() == 0);
    TEST_RESULT("PF-d Queue empty before disabled-MOSFET zero", depthOk && preZeroDepth == 0);

    motor->zeroPosition();                  // firmware: allowed (no MOSFET check)
    delay(150);
    uint8_t disabledZeroFatal = readFatalCode(motor);
    printf("Fatal code after zeroPosition (MOSFETs disabled): %d (expect 0)\n",
           disabledZeroFatal);
    // Ground truth (motor_control.c zero_position): only a non-empty queue is
    // rejected; MOSFET/closed-loop state is NOT checked -> zero is accepted.
    TEST_RESULT("PF-d zeroPosition with MOSFETs disabled is ALLOWED (no fatal error)",
                disabledZeroFatal == 0);

    float afterDisabledZero = motor->getPosition();
    printf("Position after disabled-MOSFET zero: %.4f rot\n", afterDisabledZero);
    TEST_RESULT("PF-d Commanded position ~0 after disabled-MOSFET zero",
                approxEqual(afterDisabledZero, 0.0f, NEAR_ZERO_TOL_ROT));

    // ----------------------------------------------------------------------
    // Leave the device clean and at rest.
    // ----------------------------------------------------------------------
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);
    for (uint32_t tf_drain_t0 = millis(); Serial1.available() && (millis() - tf_drain_t0) < 500; ) Serial1.read();  // bounded drain (hang-proof)
}
