#include "tf_framework.h"

// ---------------------------------------------------------------------------
// tm_sensor_consistency.cpp
//
// Raw-vs-converted sensor cross-checks. Every assertion encodes GROUND-TRUTH
// unit math read from the library's conversion source, never guesses, so a
// broken scale factor / offset / sign in the autogenerated converters shows up
// as a failed consistency check regardless of the (unknown) absolute reading.
//
// GROUND TRUTH (Arduino_library/AutoGeneratedUnitConversions.cpp/.h):
//   * Temperature (getTemperatureRaw is int16 in degrees Celsius):
//       CELSIUS    : factor 1.0            -> converted == raw
//       KELVIN     : CONVERSION_OFFSET_CELSIUS_TO_KELVIN = 273.15
//                                          -> converted == raw + 273.15
//       FAHRENHEIT : CONVERSION_FACTOR_FAHRENHEIT = 0.5555.. ,
//                    CONVERSION_OFFSET_CELSIUS_TO_FAHRENHEIT = 32
//                    FROM_INTERNAL: raw / 0.5555.. + 32  == raw*1.8 + 32
//     The temperature sensor's usable range is roughly 33..307 C; ANY reading
//     outside it is reported as EXACTLY 0 (out-of-range sentinel), so a motor
//     at room temperature reads 0 and negatives are never returned
//     (motor_commands.json "Get temperature" Description). Plausibility is
//     therefore: raw == 0 (sentinel) OR 33 <= raw <= 307.
//   * Supply voltage (getSupplyVoltageRaw is uint16, 1 count = 0.1 V):
//       VOLTS      : CONVERSION_FACTOR_VOLTS = 10.0      -> V  == raw / 10
//       MILLIVOLTS : CONVERSION_FACTOR_MILLIVOLTS = 0.01 -> mV == raw * 100
//     Cross-check: mV == V * 1000.
//   * Hall sensor position (getHallSensorPositionRaw is int64 encoder counts):
//       SHAFT_ROTATIONS: CONVERSION_FACTOR_SHAFT_ROTATIONS = 3276800.0
//                        -> converted == raw / 3276800
//
// SAFETY:
//   * Sections A (temperature) and B (voltage) command NO motion.
//   * Section C moves 0.5 rotation via a trapezoid (peak ~1.4 rot/s) that ends
//     at REST; section D runs a bounded 3 s velocity move at 1.5 rot/s that is
//     explicitly stopped with a queued zero-velocity item, so the shaft ends at
//     rest and the queue never runs out while moving (no async
//     ERROR_RUN_OUT_OF_QUEUE_ITEMS). Continuous free-shaft rotation is inherent
//     to a velocity move; velocity stays <= 1.5 rot/s (<= 3 rot/s limit).
//   * NO test-mode command (cmd 36) is used, so values 10..13 are impossible.
//   * tfGetMotor() is unique-ID (extended) addressed: every command is
//     collision-safe on the 39-motor rack; nothing is broadcast.
//   * Known bugs BUG-25/26/27/28 are not touched.
// ---------------------------------------------------------------------------

static const int NORMAL_RESET_DELAY_MS = 1500;

static const uint16_t MOSFETS_ENABLED_BIT = 1 << 1;
static const uint16_t CLOSED_LOOP_BIT     = 1 << 2;

static const float COUNTS_PER_ROTATION = 3276800.0f;  // CONVERSION_FACTOR_SHAFT_ROTATIONS

// A raw temperature is sane iff it is the out-of-range sentinel 0 or inside the
// sensor's usable 33..307 C window (motor_commands.json Get temperature).
static bool temperatureRawSane(int16_t raw) {
    return raw == 0 || (raw >= 33 && raw <= 307);
}

// Drain the motion queue (bounded), then settle. Returns true if it reached 0.
static bool waitForQueueDrain(Servomotor* motor, int maxWaitMs) {
    int waited = 0;
    while (waited < maxWaitMs) {
        uint8_t n = motor->getNQueuedItems();
        if (motor->getError() == 0 && n == 0) {
            delay(200);  // settle
            return true;
        }
        delay(50);
        waited += 50;
    }
    return false;
}

void tm_sensor_consistency(void) {
    Serial.println("test_ard_sensor_consistency: BEGIN\n");

    Servomotor* motor = tfGetMotor();

    // ---- Clean, known starting state. ----
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);  // no response during reset; don't check errors

    getStatusResponse st0 = motor->getStatus();
    printf("After reset: fatalCode=%d flags=0x%04X getErr=%d\n",
           (int)st0.fatalErrorCode, (unsigned)st0.statusFlags, motor->getError());
    TEST_RESULT("No fatal error after initial reset",
                motor->getError() == 0 && st0.fatalErrorCode == 0);

    // =======================================================================
    // SECTION A: temperature raw-vs-converted consistency (no motion).
    // =======================================================================
    printf("\n--- A: temperature raw vs converted ---\n");

    // (a) CELSIUS: converted == raw (factor 1.0). Read raw and converted close
    // together; 1 count == 1 C so tolerate at most one quantum of drift.
    motor->setTemperatureUnit(TemperatureUnit::CELSIUS);
    int16_t rawC = motor->getTemperatureRaw();
    checkMotorError(*motor, "getTemperatureRaw(C)");
    float convC = motor->getTemperature();
    checkMotorError(*motor, "getTemperature(C)");
    printf("  Celsius: raw=%d converted=%.3f\n", (int)rawC, convC);
    // GROUND TRUTH: convertTemperature FROM_INTERNAL CELSIUS returns value unchanged.
    TEST_RESULT("Temp Celsius converted == raw", approxEqual(convC, (float)rawC, 1.1f));

    // Plausibility: sentinel 0 (room temp / out of range) or in-range 33..307.
    TEST_RESULT("Temp raw is sane (0 sentinel or 33..307 C)",
                temperatureRawSane(rawC));

    // KELVIN: converted == raw + 273.15 (CONVERSION_OFFSET_CELSIUS_TO_KELVIN).
    motor->setTemperatureUnit(TemperatureUnit::KELVIN);
    int16_t rawK = motor->getTemperatureRaw();  // raw is unit-independent
    float convK = motor->getTemperature();
    checkMotorError(*motor, "getTemperature(K)");
    printf("  Kelvin: raw=%d converted=%.3f (expect raw+273.15)\n", (int)rawK, convK);
    TEST_RESULT("Temp Kelvin converted == raw + 273.15",
                approxEqual(convK, (float)rawK + 273.15f, 1.6f));

    // FAHRENHEIT: converted == raw*1.8 + 32.
    motor->setTemperatureUnit(TemperatureUnit::FAHRENHEIT);
    int16_t rawF = motor->getTemperatureRaw();
    float convF = motor->getTemperature();
    checkMotorError(*motor, "getTemperature(F)");
    printf("  Fahrenheit: raw=%d converted=%.3f (expect raw*1.8+32)\n", (int)rawF, convF);
    TEST_RESULT("Temp Fahrenheit converted == raw*1.8 + 32",
                approxEqual(convF, (float)rawF * 1.8f + 32.0f, 2.5f));

    motor->setTemperatureUnit(TemperatureUnit::CELSIUS);  // restore

    // =======================================================================
    // SECTION B: supply-voltage raw-vs-converted consistency (no motion).
    // =======================================================================
    printf("\n--- B: supply voltage raw vs converted ---\n");

    // VOLTS: V == raw / 10 (CONVERSION_FACTOR_VOLTS = 10). Separate ADC samples
    // for raw vs converted; on a stable supply they agree within a couple counts
    // (0.1 V/count), so tolerate ~0.3 V while still catching a wrong scale.
    motor->setVoltageUnit(VoltageUnit::VOLTS);
    uint16_t rawV = motor->getSupplyVoltageRaw();
    checkMotorError(*motor, "getSupplyVoltageRaw(V)");
    float volts = motor->getSupplyVoltage();
    checkMotorError(*motor, "getSupplyVoltage(V)");
    printf("  raw=%u  V=%.3f (expect raw/10)\n", (unsigned)rawV, volts);
    TEST_RESULT("Voltage VOLTS == raw / 10",
                approxEqual(volts, (float)rawV / 10.0f, 0.3f));

    // Plausibility: a supply must be present (raw > 0).
    TEST_RESULT("Supply voltage present (raw > 0)", rawV > 0);

    // MILLIVOLTS: mV == raw * 100 (CONVERSION_FACTOR_MILLIVOLTS = 0.01).
    motor->setVoltageUnit(VoltageUnit::MILLIVOLTS);
    uint16_t rawmV = motor->getSupplyVoltageRaw();
    float millivolts = motor->getSupplyVoltage();
    checkMotorError(*motor, "getSupplyVoltage(mV)");
    printf("  raw=%u  mV=%.1f (expect raw*100)\n", (unsigned)rawmV, millivolts);
    TEST_RESULT("Voltage MILLIVOLTS == raw * 100",
                approxEqual(millivolts, (float)rawmV * 100.0f, 350.0f));

    // Cross-check the two unit views agree: mV == V * 1000.
    TEST_RESULT("Voltage mV == V * 1000",
                approxEqual(millivolts, volts * 1000.0f, 350.0f));

    motor->setVoltageUnit(VoltageUnit::VOLTS);  // restore

    // =======================================================================
    // SECTION C: hall position raw vs converted across a 0.5-rotation move.
    // Requires closed-loop control; abort gracefully (no motion) if the motor
    // is not calibrated.
    // =======================================================================
    printf("\n--- C: hall position raw vs converted over 0.5 rot ---\n");

    motor->setPositionUnit(PositionUnit::SHAFT_ROTATIONS);
    motor->setVelocityUnit(VelocityUnit::ROTATIONS_PER_SECOND);
    motor->setTimeUnit(TimeUnit::SECONDS);

    motor->enableMosfets();
    checkMotorError(*motor, "enableMosfets");
    delay(300);  // let the commutation-alignment transient settle

    motor->goToClosedLoop();
    // Do NOT checkMotorError: an uncalibrated motor raises a fatal error here.
    bool closedLoop = false;
    for (int elapsed = 0; elapsed < 3000; elapsed += 100) {
        getStatusResponse s = motor->getStatus();
        if (motor->getError() != 0 || s.fatalErrorCode != 0) break;
        if (s.statusFlags & CLOSED_LOOP_BIT) { closedLoop = true; break; }
        delay(100);
    }
    printf("  closed loop entered = %d\n", (int)closedLoop);

    if (!closedLoop) {
        // Motor almost certainly not calibrated: report and recover cleanly.
        TEST_RESULT("C/D skipped: closed loop not entered (motor calibrated?)", false);
        motor->systemReset();
        delay(NORMAL_RESET_DELAY_MS);
        motor->systemReset();
        delay(NORMAL_RESET_DELAY_MS);
        return;
    }

    motor->zeroPosition();
    checkMotorError(*motor, "zeroPosition");
    delay(200);

    int64_t rawBefore  = motor->getHallSensorPositionRaw();
    checkMotorError(*motor, "getHallSensorPositionRaw(before)");
    float   convBefore = motor->getHallSensorPosition();
    checkMotorError(*motor, "getHallSensorPosition(before)");

    // 0.5 rotation over 0.6 s -> trapezoid peak ~1.4 rot/s (<= 3), ends at rest.
    motor->trapezoidMove(0.5f, 0.6f);
    checkMotorError(*motor, "trapezoidMove(0.5)");
    bool drained = waitForQueueDrain(motor, 4000);
    printf("  queue drained after move = %d\n", (int)drained);

    int64_t rawAfter  = motor->getHallSensorPositionRaw();
    checkMotorError(*motor, "getHallSensorPositionRaw(after)");
    float   convAfter = motor->getHallSensorPosition();
    checkMotorError(*motor, "getHallSensorPosition(after)");

    int64_t rawChange  = rawAfter - rawBefore;
    float   convChange = convAfter - convBefore;
    float   expectedConv = (float)rawChange / COUNTS_PER_ROTATION;  // GROUND TRUTH
    printf("  rawBefore=%lld rawAfter=%lld rawChange=%lld\n",
           (long long)rawBefore, (long long)rawAfter, (long long)rawChange);
    printf("  convChange=%.5f expected(raw/3276800)=%.5f\n", convChange, expectedConv);

    // (c) converted change == raw change / 3276800 within 1% (+ small floor for
    // closed-loop holding jitter between the raw and converted reads).
    float tol = std::fabs(expectedConv) * 0.01f + 0.002f;
    TEST_RESULT("Hall converted change == raw change / 3276800 (within 1%)",
                approxEqual(convChange, expectedConv, tol));

    // Sanity: the motor actually executed the commanded ~0.5 rotation.
    TEST_RESULT("Hall change reflects ~0.5 rot move",
                std::fabs(convChange) >= 0.35f && std::fabs(convChange) <= 0.65f);

    // =======================================================================
    // SECTION D: temperature before vs after a 3 s continuous velocity move.
    // Sensor must stay sane under load and must not implausibly drop.
    // =======================================================================
    printf("\n--- D: temperature across a 3 s velocity move ---\n");

    int16_t tempBefore = motor->getTemperatureRaw();
    checkMotorError(*motor, "getTemperatureRaw(before load)");
    printf("  temp before = %d C\n", (int)tempBefore);
    TEST_RESULT("Temp before load is sane (0 sentinel or 33..307 C)",
                temperatureRawSane(tempBefore));

    // 1.5 rot/s for 0.6 s (total travel ~0.9 rot, within the <=~1.2 rot rack
    // motion budget — a 4.5-rot travel could wrap the rack pulley/belt), then a
    // queued zero-velocity item so the shaft ends at rest and the queue never
    // runs out while moving.
    motor->moveWithVelocity(1.5f, 0.6f);
    checkMotorError(*motor, "moveWithVelocity(1.5, 0.6)");
    motor->moveWithVelocity(0.0f, 0.5f);  // decelerate/hold to rest
    checkMotorError(*motor, "moveWithVelocity(0, 0.5)");
    bool drained2 = waitForQueueDrain(motor, 6000);
    printf("  queue drained after velocity move = %d\n", (int)drained2);

    int16_t tempAfter = motor->getTemperatureRaw();
    checkMotorError(*motor, "getTemperatureRaw(after load)");
    printf("  temp after = %d C\n", (int)tempAfter);
    TEST_RESULT("Temp after load is sane (0 sentinel or 33..307 C)",
                temperatureRawSane(tempAfter));

    // The sensor must not implausibly cool over a brief 3 s move (allow 2 C of
    // quantization / sentinel wobble). A short move barely heats a room-temp
    // PCB, so both readings are typically the 0 sentinel: 0 >= 0 - 2 holds.
    TEST_RESULT("Temp after >= before - 2 C (sensor sane under load)",
                (float)tempAfter >= (float)tempBefore - 2.0f);

    // ---- Leave the device clean and at rest. ----
    motor->disableMosfets();
    checkMotorError(*motor, "disableMosfets");
    motor->systemReset();
    delay(NORMAL_RESET_DELAY_MS);
}
