#include "tf_motion_helpers.h"

// ---------------------------------------------------------------------------
// tm_telemetry_conversions.cpp
//
// THE TELEMETRY UNIT CONVERSIONS, CHECKED AGAINST LIVE DEVICE DATA.
//
// Two telemetry commands return a scalar that the library then re-expresses in
// whatever unit the caller selected. Both conversions happen ENTIRELY on the
// host side -- setVoltageUnit() and setTemperatureUnit() put nothing on the
// bus, they only write a private member (Servomotor.cpp:114, :119) -- and the
// converted getter is a thin wrapper that calls the raw getter and pushes the
// result through one function:
//
//     getSupplyVoltage() = convertVoltage(getSupplyVoltageRaw(), unit, FROM_INTERNAL)
//                                                     (Servomotor.cpp:1639)
//     getTemperature()   = convertTemperature(getTemperatureRaw(), unit, FROM_INTERNAL)
//                                                     (Servomotor.cpp:1791)
//
// The firmware's side of the contract, verified in the source:
//
//   * Supply voltage (cmd 38). main.c:852 answers with a u16 produced by
//     get_supply_voltage_volts_times_10() (main.c:862), which is
//     (adc_sum * SUPPLY_VOLTAGE_CALIBRATION_CONSTANT) >> 20 (ADC.c:295-301).
//     The wire unit is therefore DECIVOLTS -- volts times ten.
//     convertVoltage divides by CONVERSION_FACTOR_VOLTS = 10 for VOLTS and by
//     CONVERSION_FACTOR_MILLIVOLTS = 0.01 for MILLIVOLTS
//     (AutoGeneratedUnitConversions.cpp:261-292), so the three forms are
//     locked together:  raw  ==  volts * 10  ==  millivolts / 100.
//
//   * Temperature (cmd 20). main.c:961 answers with an i16 from
//     get_temperature_degrees_C() (main.c:971), i.e. WHOLE DEGREES CELSIUS
//     straight out of a lookup table (temperature.c:27-54). CELSIUS is
//     therefore the IDENTITY conversion, and Fahrenheit/Kelvin are derived
//     from it by  F = C/0.555555556 + 32  and  K = C + 273.15
//     (AutoGeneratedUnitConversions.cpp:295-333).
//
// WHAT THIS MODULE ASSERTS, and how it differs from what already exists.
// tm_telemetry and tm_temperature check that a SINGLE reading is PLAUSIBLE --
// "the supply is between 6 and 40 V", "the sensor says something between 5 and
// 85 C". A conversion that is wrong by a constant factor sails straight
// through such a check: 24.1 V and 24100 mV are both plausible numbers.
// tm_unit_conversions and tm_units_roundtrip do check the arithmetic, but on
// invented constants with no device in the loop, so a library that converts
// perfectly and then reads the wrong field, or reads a stale value, or applies
// the conversion twice, still passes them.
//
// The property here is the one that catches all of those:
//
//     For ONE reading taken from the machine, every unit the library offers
//     must be an exact re-expression of the same number -- and converting the
//     answer back must reproduce the bytes the device actually sent.
//
// The technique that makes this sharp is BRACKETING. Both sensors drift: the
// supply moves with load and the temperature quantises to whole degrees and can
// step at any moment. A naive "read in C, read in F, compare" fails whenever
// the sensor steps between the two reads, which looks exactly like a conversion
// bug. So every comparison here reads the RAW value, then the converted forms,
// then the RAW value again, and only makes the strict claim when the two raw
// reads are identical -- proof the underlying measurement never moved. Trials
// where it did move are reported and skipped, and a separate assertion requires
// that at least one trial was stable so the section cannot pass vacuously.
//
// BRACKETING IS NECESSARY BUT NOT SUFFICIENT, and that distinction decides how
// the assertions below are phrased. A bracket proves the two ENDPOINT reads
// agree; it cannot prove the reading never moved and came BACK. The soak run
// measured this supply sitting at 24.1-24.2 V, i.e. genuinely toggling between
// raw 241 and raw 242, so a sequence 241 / 242 / 241 satisfies the bracket
// while the converted read in the middle legitimately disagrees by a whole
// decivolt. Demanding that EVERY stable trial agree to a millivolt would
// therefore fail on a perfectly healthy machine -- the exact class of false
// alarm this campaign has already burned four debugging cycles on.
//
// So each family is judged two ways instead:
//
//   BEST OF N   -- at least one stable trial must agree to float precision.
//                  A conversion that is wrong by a factor, an offset, or that
//                  reads the wrong field is wrong by orders of magnitude on
//                  EVERY trial, so it can never satisfy this even once.
//   BOUNDED     -- no stable trial may disagree by more than one sensor step
//                  plus slop. This is what a mid-bracket bounce can produce and
//                  nothing else, so it catches an intermittently gross answer
//                  without failing on a supply that moved by 0.1 V.
//
// Values carried forward into the round-trip sections are taken only from a
// trial that satisfied the strict form, so those comparisons stay tight.
//
// A useful consequence: these assertions are independent of what the sensor
// actually reads. If the temperature came back as the 0 out-of-range sentinel
// (temperature.c:31-37 returns exactly 0 outside the table's 33..307 C span),
// C=0 / F=32 / K=273.15 still satisfy every relationship. Sensor plausibility
// is asserted once, separately, so a cold motor produces one clearly-labelled
// failure instead of corrupting the conversion evidence.
//
// SAFETY. Telemetry reads are pure: they touch no motor state and queue
// nothing. The MOSFETs are never enabled, so nothing physically turns anywhere.
// The single move in section 8 exists only to prove the conversions still hold
// while the planner is busy; it reads the COMMANDED position, which advances
// with the output stage off, and it is drained with tfhDrain() rather than a
// computed wait. No broadcasts and no alias writes, so this is safe on the
// shared 35-motor rack. Every section ends by resetting the motor.
// ---------------------------------------------------------------------------

// Plausible supply window, expressed in the DECIVOLTS the wire actually carries.
static const uint16_t VOLT_RAW_MIN = 60;    //  6.0 V
static const uint16_t VOLT_RAW_MAX = 400;   // 40.0 V

// The temperature lookup table spans 33..307 C (temperature_lookup_table.h:
// first entry 4296 >> 7 == 33, last 33862 >> 7 == 264 plus up to 43 of slope),
// and temperature.c:31-37 returns exactly 0 for anything outside it.
static const int16_t TEMP_TABLE_MIN_C = 33;
static const int16_t TEMP_TABLE_MAX_C = 307;

static const int N_TRIALS    = 8;    // bracketed conversion trials per family
static const int N_STABILITY = 12;   // repeated raw samples for the drift check

// STRICT tolerances, used for the best-of-N claim. These are float-arithmetic
// slop, NOT measurement slop: the comparison is against a raw integer, so the
// only permitted error is the rounding of a 24-bit mantissa. At 24100 mV a
// float ULP is about 0.002, so 1 mV is roughly a 500x margin and still far too
// tight to hide a wrong factor. (Fahrenheit gets a little more room because the
// library divides by the float constant 0.555555556f rather than multiplying by
// 1.8, and 1/0.555555556f is 1.7999998 rather than 1.8 exactly; at the top of
// the sensor's range that is about 7e-5 degF of unavoidable disagreement.)
static const float TOL_VOLTS = 0.001f;   // volts,    vs raw/10
static const float TOL_MV    = 1.0f;     // millivolts, vs raw*100
static const float TOL_RAW   = 0.01f;    // decivolts, on the way back
static const float TOL_DEGC  = 0.01f;    // degrees C
static const float TOL_DEGF  = 0.02f;    // degrees F (1 degC == 1.8 degF)

// BOUNDED tolerances, applied to every stable trial. One sensor step is 0.1 V
// for the supply (the wire unit is decivolts) and 1 degC for the temperature
// (the wire unit is whole degrees). These allow two steps, which is what a
// reading that moved and came back INSIDE a bracket can produce, and nothing
// more -- a wrong conversion factor is off by a factor of ten or a thousand and
// blows straight through them.
static const float TOL_VOLTS_BOUND = 0.25f;    // volts
static const float TOL_MV_BOUND    = 250.0f;   // millivolts
static const float TOL_DEGC_BOUND  = 2.5f;     // degrees C
static const float TOL_DEGF_BOUND  = 4.5f;     // degrees F (2.5 degC == 4.5 degF)

void tm_telemetry_conversions(void) {
    Serial.println("tm_telemetry_conversions: BEGIN\n");
    Servomotor* m = tfGetMotor();

    // =====================================================================
    // 1. THE RAW SUPPLY READING IS A DECIVOLT COUNT, AND IT HOLDS STILL.
    //    Everything after this compares converted values against this raw
    //    number, so it has to be trustworthy first: it must answer, it must
    //    be a plausible decivolt count rather than volts or millivolts, and
    //    it must not be wandering between reads. A reading that drifted by
    //    volts from sample to sample would make every later comparison
    //    meaningless, and a reading of 0 would mean the ADC never produced
    //    data and the whole reply is a placeholder.
    // =====================================================================
    printf("\n--- 1. the raw supply reading is decivolts and holds still ---\n");
    {
        tfhReset(m);
        m->setVoltageUnit(VoltageUnit::VOLTS);
        delay(200);                       // supply ADC settle after the reset

        uint16_t raw0 = m->getSupplyVoltageRaw();
        bool firstOk = (m->getError() == 0);

        uint16_t lo = raw0, hi = raw0;
        bool allAnswered = firstOk;
        bool neverZero = (raw0 != 0);
        for (int i = 0; i < N_STABILITY; i++) {
            uint16_t r = m->getSupplyVoltageRaw();
            if (m->getError() != 0) { allAnswered = false; break; }
            if (r == 0) neverZero = false;
            if (r < lo) lo = r;
            if (r > hi) hi = r;
            delay(30);
        }
        printf("   raw supply = %u decivolts (%.1f V); %d samples span %u..%u (%u decivolts)\n",
               (unsigned)raw0, (double)raw0 / 10.0, N_STABILITY,
               (unsigned)lo, (unsigned)hi, (unsigned)(hi - lo));

        TEST_RESULT("the raw supply voltage command answers without a communication error",
                    firstOk);
        TEST_RESULT("the raw supply voltage is a plausible decivolt count, not volts or millivolts",
                    raw0 >= VOLT_RAW_MIN && raw0 <= VOLT_RAW_MAX);
        TEST_RESULT("twelve consecutive raw supply readings all answer", allAnswered);
        TEST_RESULT("the raw supply reading is never the zero placeholder", neverZero);
        // 10 decivolts == 1.0 V. The soak run measured this sensor sitting at
        // 24.1-24.2 V, i.e. a spread of one decivolt, so this is generous.
        TEST_RESULT("twelve consecutive raw supply readings span less than one volt",
                    allAnswered && (hi - lo) <= 10);
    }

    // =====================================================================
    // 2. VOLTS IS EXACTLY THE RAW DECIVOLTS DIVIDED BY TEN. The first half
    //    of the voltage contract. This is the relationship a user relies on
    //    without ever thinking about it, and it is the one a change to
    //    CONVERSION_FACTOR_VOLTS, or a firmware change to the wire unit,
    //    would silently break while leaving every plausibility check happy.
    //    Also checked here: selecting a unit is a host-side act, so it must
    //    not perturb the raw reading at all.
    // =====================================================================
    printf("\n--- 2. VOLTS is the raw decivolts divided by ten ---\n");
    int stableV = 0;
    int cleanV  = 0;                 // stable trials that ALSO matched exactly
    uint16_t lastStableRawV = 0;
    float lastStableVolts = 0.0f, lastStableMv = 0.0f;
    {
        bool voltsPlausible = true;
        bool rawUndisturbed = true;
        bool allAnsweredV = true;
        float worstVoltsErr = 0.0f;
        float bestVoltsErr = 1e9f;

        for (int t = 0; t < N_TRIALS; t++) {
            m->setVoltageUnit(VoltageUnit::VOLTS);
            uint16_t rawBefore = m->getSupplyVoltageRaw();
            bool ok = (m->getError() == 0);
            float volts = m->getSupplyVoltage();
            ok = ok && (m->getError() == 0);
            m->setVoltageUnit(VoltageUnit::MILLIVOLTS);
            float mv = m->getSupplyVoltage();
            ok = ok && (m->getError() == 0);
            uint16_t rawAfter = m->getSupplyVoltageRaw();
            ok = ok && (m->getError() == 0);

            // The raw getter must be indifferent to the selected unit: it was
            // read once with VOLTS selected and once with MILLIVOLTS selected.
            if (!ok) { rawUndisturbed = false; allAnsweredV = false; }
            if (ok) {
                if (rawBefore < VOLT_RAW_MIN || rawBefore > VOLT_RAW_MAX ||
                    rawAfter < VOLT_RAW_MIN || rawAfter > VOLT_RAW_MAX) rawUndisturbed = false;
                // Only judge plausibility on a reply that actually arrived: the
                // library returns 0 from a failed getter, which would otherwise
                // be reported as an implausible voltage rather than as the
                // communication failure it is.
                if (volts < 6.0f || volts > 40.0f) voltsPlausible = false;
            }

            bool stable = ok && (rawBefore == rawAfter);
            if (stable) {
                float expect = (float)rawBefore / 10.0f;
                float err = std::fabs(volts - expect);
                if (err > worstVoltsErr) worstVoltsErr = err;
                if (err < bestVoltsErr) bestVoltsErr = err;
                stableV++;
                // Carry forward ONLY a trial where BOTH converted reads matched
                // the raw value exactly, so section 4 is comparing converted
                // values and a raw value that provably came from the same
                // measurement. `mv` is a separate bus transaction from `volts`,
                // so it has to be checked separately -- a trial can be exact in
                // volts and still have caught a bounce in the millivolt read.
                if (err <= TOL_VOLTS &&
                    std::fabs(mv - (float)rawBefore * 100.0f) <= TOL_MV) {
                    cleanV++;
                    lastStableRawV = rawBefore;
                    lastStableVolts = volts;
                    lastStableMv = mv;
                }
            }
            printf("   trial %d: raw %u/%u %s -> %.4f V, %.2f mV (expect %.4f V)\n",
                   t + 1, (unsigned)rawBefore, (unsigned)rawAfter,
                   stable ? "STABLE" : "drifted", (double)volts, (double)mv,
                   (double)rawBefore / 10.0);
            delay(40);
        }
        m->setVoltageUnit(VoltageUnit::VOLTS);
        printf("   %d of %d trials stable, %d exact; best volts error %.6f V, worst %.6f V\n",
               stableV, N_TRIALS, cleanV,
               (double)(stableV > 0 ? bestVoltsErr : 0.0f), (double)worstVoltsErr);

        TEST_RESULT("at least one bracketed trial caught the supply reading holding still",
                    stableV > 0);
        TEST_RESULT("every trial's supply reads answered without a communication error",
                    allAnsweredV);
        // BEST OF N. A conversion that is wrong by a factor cannot match even
        // once; a supply that bounced inside a bracket cannot spoil every trial.
        TEST_RESULT("getSupplyVoltage in VOLTS equals the raw decivolts divided by ten on at least one reading",
                    cleanV > 0);
        // BOUNDED. Weaker than the above on purpose: the only disagreement a
        // healthy machine can produce here is the supply stepping by a decivolt
        // between two bus transactions inside the bracket.
        TEST_RESULT("no stable trial disagreed with the raw decivolts by more than a couple of sensor steps",
                    stableV > 0 && worstVoltsErr <= TOL_VOLTS_BOUND);
        TEST_RESULT("the volts reading lands in the plausible 6 to 40 V band on every trial",
                    voltsPlausible);
        TEST_RESULT("choosing a voltage unit does not disturb what the raw command returns",
                    rawUndisturbed);
    }

    // =====================================================================
    // 3. MILLIVOLTS IS THE RAW TIMES A HUNDRED, AND VOLTS TIMES A THOUSAND.
    //    The second half of the voltage contract, and the more interesting
    //    one: MILLIVOLTS is reached by DIVIDING by 0.01 rather than by
    //    multiplying by 100 (AutoGeneratedUnitConversions.cpp:285), so the
    //    two units travel different arithmetic paths to the same physical
    //    quantity. Requiring them to agree to a millivolt on the same reading
    //    is what makes the second path real rather than assumed.
    // =====================================================================
    printf("\n--- 3. MILLIVOLTS is the raw times a hundred, and volts times a thousand ---\n");
    {
        bool mvPlausible = true;
        bool allAnsweredMv = true;
        float worstMvErr = 0.0f, worstCrossErr = 0.0f;
        float bestMvErr = 1e9f, bestCrossErr = 1e9f;
        int stable = 0, cleanRaw = 0, cleanCross = 0;

        for (int t = 0; t < N_TRIALS; t++) {
            m->setVoltageUnit(VoltageUnit::MILLIVOLTS);
            uint16_t rawBefore = m->getSupplyVoltageRaw();
            bool ok = (m->getError() == 0);
            float mv = m->getSupplyVoltage();
            ok = ok && (m->getError() == 0);
            m->setVoltageUnit(VoltageUnit::VOLTS);
            float volts = m->getSupplyVoltage();
            ok = ok && (m->getError() == 0);
            uint16_t rawAfter = m->getSupplyVoltageRaw();
            ok = ok && (m->getError() == 0);

            if (!ok) allAnsweredMv = false;
            // As in section 2: a failed getter returns 0, so only a reply that
            // arrived can be judged for plausibility.
            if (ok && (mv < 6000.0f || mv > 40000.0f)) mvPlausible = false;

            if (ok && rawBefore == rawAfter) {
                stable++;
                float expectMv = (float)rawBefore * 100.0f;
                float errRaw = std::fabs(mv - expectMv);
                float errCross = std::fabs(mv - volts * 1000.0f);
                if (errRaw > worstMvErr) worstMvErr = errRaw;
                if (errCross > worstCrossErr) worstCrossErr = errCross;
                if (errRaw < bestMvErr) bestMvErr = errRaw;
                if (errCross < bestCrossErr) bestCrossErr = errCross;
                if (errRaw <= TOL_MV) cleanRaw++;
                if (errCross <= TOL_MV) cleanCross++;
                printf("   trial %d: raw %u STABLE -> %.3f mV (expect %.1f), volts*1000 = %.3f\n",
                       t + 1, (unsigned)rawBefore, (double)mv, (double)expectMv,
                       (double)(volts * 1000.0f));
            } else {
                printf("   trial %d: raw %u/%u drifted -> %.3f mV (skipped)\n",
                       t + 1, (unsigned)rawBefore, (unsigned)rawAfter, (double)mv);
            }
            delay(40);
        }
        m->setVoltageUnit(VoltageUnit::VOLTS);
        printf("   %d stable trials (%d exact vs raw, %d exact vs volts); mV-vs-raw best %.4f worst %.4f, "
               "mV-vs-volts best %.4f worst %.4f\n",
               stable, cleanRaw, cleanCross,
               (double)(stable > 0 ? bestMvErr : 0.0f), (double)worstMvErr,
               (double)(stable > 0 ? bestCrossErr : 0.0f), (double)worstCrossErr);

        TEST_RESULT("every trial's millivolt reads answered without a communication error",
                    allAnsweredMv);
        // Best of N, then bounded -- see the header. The volts and millivolts
        // reads are two separate bus transactions, so the supply can genuinely
        // step by a decivolt (100 mV) between them on a healthy machine.
        TEST_RESULT("getSupplyVoltage in MILLIVOLTS equals the raw decivolts times a hundred on at least one reading",
                    cleanRaw > 0);
        TEST_RESULT("millivolts and volts describe the same supply to the millivolt on at least one reading",
                    cleanCross > 0);
        TEST_RESULT("no stable trial's millivolts disagreed with the raw decivolts by more than a couple of sensor steps",
                    stable > 0 && worstMvErr <= TOL_MV_BOUND);
        TEST_RESULT("no stable trial's millivolts and volts disagreed by more than a couple of sensor steps",
                    stable > 0 && worstCrossErr <= TOL_MV_BOUND);
        TEST_RESULT("the millivolt reading lands in the plausible 6000 to 40000 mV band",
                    mvPlausible);
    }

    // =====================================================================
    // 4. THE VOLTAGE CONVERSION IS INVERTIBLE ON LIVE DATA. Pushing the
    //    number the user was given back through the conversion must land on
    //    the bytes the device actually sent. A one-way check can be satisfied
    //    by a conversion that loses information; this one cannot. Round-trips
    //    are already checked on invented constants in tm_units_roundtrip --
    //    what is new here is that the starting point is a real device reading
    //    that arrived over the bus.
    //
    //    Also asserted: the unit selection lives in the library, not the
    //    motor, so resetting the motor must not change it. A user who resets
    //    and then reads without re-selecting must not silently get decivolts.
    // =====================================================================
    printf("\n--- 4. the voltage conversion inverts, and the unit survives a device reset ---\n");
    {
        float backFromVolts = convertVoltage(lastStableVolts, VoltageUnit::VOLTS,
                                             ConversionDirection::TO_INTERNAL);
        float backFromMv = convertVoltage(lastStableMv, VoltageUnit::MILLIVOLTS,
                                          ConversionDirection::TO_INTERNAL);
        printf("   last stable raw %u: volts %.4f -> %.4f, millivolts %.2f -> %.4f\n",
               (unsigned)lastStableRawV, (double)lastStableVolts, (double)backFromVolts,
               (double)lastStableMv, (double)backFromMv);
        // Gated on cleanV, not stableV: lastStable* is only recorded from a
        // trial whose forward conversion matched exactly, so the raw value and
        // the converted values here provably describe one measurement. Gating
        // on stableV alone would let a trial where the supply bounced mid-
        // bracket set up a round-trip that fails by a whole decivolt.
        TEST_RESULT("the VOLTS reading converts back to the raw decivolts the device sent",
                    cleanV > 0 &&
                    std::fabs(backFromVolts - (float)lastStableRawV) <= TOL_RAW);
        TEST_RESULT("the MILLIVOLTS reading converts back to the raw decivolts the device sent",
                    cleanV > 0 &&
                    std::fabs(backFromMv - (float)lastStableRawV) <= TOL_RAW);

        // Select millivolts, reset the MOTOR, and read again without
        // re-selecting. tfhReset only re-establishes the motion units, so the
        // voltage unit is untouched and must still be in force.
        m->setVoltageUnit(VoltageUnit::MILLIVOLTS);
        tfhReset(m);
        delay(200);
        float mvAfterReset = m->getSupplyVoltage();
        bool ok = (m->getError() == 0);
        m->setVoltageUnit(VoltageUnit::VOLTS);
        printf("   after a device reset, still reading %.1f mV\n", (double)mvAfterReset);
        TEST_RESULT("the voltage unit is a library setting and survives a device reset",
                    ok && mvAfterReset >= 6000.0f && mvAfterReset <= 40000.0f);
    }

    // =====================================================================
    // 5. THE RAW TEMPERATURE IS WHOLE DEGREES CELSIUS, AND IT HOLDS STILL.
    //    Same premise-first approach as section 1. The firmware returns
    //    either a value inside the lookup table's 33..307 C span or exactly
    //    0 as an out-of-range sentinel (temperature.c:31-37) -- there is no
    //    third possibility, and a reading of, say, 12 would mean the table or
    //    the ADC scaling had changed underneath us. Whether the sensor is
    //    reporting a real measurement at all is asserted separately, so that
    //    a genuinely cold motor produces one labelled failure rather than
    //    invalidating the conversion evidence that follows.
    // =====================================================================
    printf("\n--- 5. the raw temperature is whole degrees Celsius and holds still ---\n");
    {
        tfhReset(m);
        m->setTemperatureUnit(TemperatureUnit::CELSIUS);
        delay(200);

        int16_t raw0 = m->getTemperatureRaw();
        bool firstOk = (m->getError() == 0);

        int16_t lo = raw0, hi = raw0;
        bool allAnswered = firstOk;
        for (int i = 0; i < N_STABILITY; i++) {
            int16_t r = m->getTemperatureRaw();
            if (m->getError() != 0) { allAnswered = false; break; }
            if (r < lo) lo = r;
            if (r > hi) hi = r;
            delay(30);
        }
        printf("   raw temperature = %d C; %d samples span %d..%d (%d degrees)\n",
               (int)raw0, N_STABILITY, (int)lo, (int)hi, (int)(hi - lo));

        TEST_RESULT("the raw temperature command answers without a communication error",
                    firstOk);
        TEST_RESULT("the raw temperature is either the zero sentinel or inside the table's 33 to 307 C span",
                    raw0 == 0 || (raw0 >= TEMP_TABLE_MIN_C && raw0 <= TEMP_TABLE_MAX_C));
        // ENVIRONMENT PREMISE, not a firmware claim. The lookup table cannot
        // express anything below 33 C, so a board genuinely colder than that
        // reports the 0 sentinel and this one assertion fails while every
        // conversion assertion below still holds (0 C / 32 F / 273.15 K satisfy
        // them all). It is the same premise the existing tm_temperature already
        // makes when it requires 5 < C < 85, and that module is green on both
        // the bench motor and the rack.
        TEST_RESULT("the sensor is reporting a real measurement rather than the zero out-of-range sentinel",
                    raw0 != 0);
        TEST_RESULT("twelve consecutive raw temperature readings all answer", allAnswered);
        TEST_RESULT("twelve consecutive raw temperature readings span no more than three degrees",
                    allAnswered && (hi - lo) <= 3);
    }

    // =====================================================================
    // 6. ALL THREE TEMPERATURE UNITS DESCRIBE THE SAME READING. The core
    //    claim. Because the wire carries whole degrees Celsius, CELSIUS must
    //    be the exact identity -- getTemperature() and getTemperatureRaw()
    //    must be the same number, not merely close -- and Fahrenheit and
    //    Kelvin must be the textbook functions of it. Bracketing is essential
    //    here: the sensor quantises to 1 C and can step between two reads,
    //    which without bracketing is indistinguishable from a broken
    //    conversion. That is precisely why the existing tm_temperature has to
    //    allow 2.5 degF of slack; with bracketing plus best-of-N this module
    //    can demand 0.02 degF on at least one reading and still be robust.
    //
    //    The bracket here spans FIVE bus transactions (raw, C, F, K, raw), so
    //    it is the widest in the module and the most likely to close around a
    //    reading that stepped by a degree and came back. Hence the best-of-N /
    //    bounded pairing described in the file header rather than a demand that
    //    every stable trial agree.
    // =====================================================================
    printf("\n--- 6. Celsius, Fahrenheit and Kelvin all describe one reading ---\n");
    int stableT = 0;
    int cleanT  = 0;                 // stable trials where all three matched
    int16_t lastStableRawT = 0;
    float lastStableC = 0.0f, lastStableF = 0.0f, lastStableK = 0.0f;
    {
        int celsiusExact = 0, fahrenheitExact = 0, kelvinExact = 0;
        bool fAboveC = true;
        bool aboveAbsoluteZero = true;
        bool allAnsweredT = true;
        float worstC = 0.0f, worstF = 0.0f, worstK = 0.0f;

        for (int t = 0; t < N_TRIALS; t++) {
            int16_t rawBefore = m->getTemperatureRaw();
            bool ok = (m->getError() == 0);
            m->setTemperatureUnit(TemperatureUnit::CELSIUS);
            float c = m->getTemperature();
            ok = ok && (m->getError() == 0);
            m->setTemperatureUnit(TemperatureUnit::FAHRENHEIT);
            float f = m->getTemperature();
            ok = ok && (m->getError() == 0);
            m->setTemperatureUnit(TemperatureUnit::KELVIN);
            float k = m->getTemperature();
            ok = ok && (m->getError() == 0);
            int16_t rawAfter = m->getTemperatureRaw();
            ok = ok && (m->getError() == 0);

            // Only judge the ordering relations on replies that arrived: a
            // failed getter returns 0, which would make f <= c and report a
            // communication fault as a broken Fahrenheit conversion.
            if (!ok) allAnsweredT = false;
            if (ok) {
                if (f <= c) fAboveC = false;              // true for anything above -40 C
                if (k < 0.0f) aboveAbsoluteZero = false;  // Kelvin cannot be negative
            }

            bool stable = ok && (rawBefore == rawAfter);
            if (stable) {
                float expectF = (float)rawBefore * 1.8f + 32.0f;
                float expectK = (float)rawBefore + 273.15f;
                float errC = std::fabs(c - (float)rawBefore);
                float errF = std::fabs(f - expectF);
                float errK = std::fabs(k - expectK);
                if (errC > worstC) worstC = errC;
                if (errF > worstF) worstF = errF;
                if (errK > worstK) worstK = errK;
                if (errC <= TOL_DEGC) celsiusExact++;
                if (errF <= TOL_DEGF) fahrenheitExact++;
                if (errK <= TOL_DEGC) kelvinExact++;
                stableT++;
                // Carry forward only a trial in which all three units agreed
                // with the same raw integer, so section 7's round-trip is
                // comparing values that provably describe one measurement.
                if (errC <= TOL_DEGC && errF <= TOL_DEGF && errK <= TOL_DEGC) {
                    cleanT++;
                    lastStableRawT = rawBefore;
                    lastStableC = c;
                    lastStableF = f;
                    lastStableK = k;
                }
                printf("   trial %d: raw %d STABLE -> C %.3f, F %.3f (expect %.3f), K %.3f (expect %.3f)\n",
                       t + 1, (int)rawBefore, (double)c, (double)f, (double)expectF,
                       (double)k, (double)expectK);
            } else {
                printf("   trial %d: raw %d/%d drifted -> C %.3f F %.3f K %.3f (skipped)\n",
                       t + 1, (int)rawBefore, (int)rawAfter,
                       (double)c, (double)f, (double)k);
            }
            delay(40);
        }
        m->setTemperatureUnit(TemperatureUnit::CELSIUS);
        printf("   %d of %d trials stable (%d/%d/%d exact in C/F/K); worst C %.5f, F %.5f, K %.5f\n",
               stableT, N_TRIALS, celsiusExact, fahrenheitExact, kelvinExact,
               (double)worstC, (double)worstF, (double)worstK);

        TEST_RESULT("at least one bracketed trial caught the temperature sensor holding still",
                    stableT > 0);
        TEST_RESULT("every trial's temperature reads answered without a communication error",
                    allAnsweredT);
        // Best of N: a broken conversion is wrong on every trial, so one exact
        // agreement is proof; a 1 degC step inside the bracket only spoils some.
        TEST_RESULT("CELSIUS is the identity conversion on at least one reading: getTemperature equals getTemperatureRaw",
                    celsiusExact > 0);
        TEST_RESULT("getTemperature in FAHRENHEIT equals Celsius times 1.8 plus 32 on at least one reading",
                    fahrenheitExact > 0);
        TEST_RESULT("getTemperature in KELVIN equals Celsius plus 273.15 on at least one reading",
                    kelvinExact > 0);
        // Bounded: the only disagreement a healthy sensor can produce inside a
        // bracket is a step or two of its own 1 degC quantisation.
        TEST_RESULT("no stable trial's Celsius disagreed with the raw degrees by more than a couple of sensor steps",
                    stableT > 0 && worstC <= TOL_DEGC_BOUND);
        TEST_RESULT("no stable trial's Fahrenheit disagreed by more than a couple of sensor steps",
                    stableT > 0 && worstF <= TOL_DEGF_BOUND);
        TEST_RESULT("no stable trial's Kelvin disagreed by more than a couple of sensor steps",
                    stableT > 0 && worstK <= TOL_DEGC_BOUND);
        TEST_RESULT("the Fahrenheit reading always exceeds the Celsius reading above minus forty",
                    allAnsweredT && fAboveC);
        TEST_RESULT("the Kelvin reading is never below absolute zero",
                    allAnsweredT && aboveAbsoluteZero);
    }

    // =====================================================================
    // 7. EVERY TEMPERATURE UNIT ROUND-TRIPS ON LIVE DATA, AND THE THREE
    //    AGREE WITH EACH OTHER. Fahrenheit is the interesting case: it is the
    //    only conversion in the library with BOTH a scale factor and an
    //    offset, and offsets are where sign and ordering mistakes live -- the
    //    inverse applies the offset first and the factor second
    //    (AutoGeneratedUnitConversions.cpp:307), the opposite order from the
    //    forward direction. Recovering the device's own integer is the test
    //    that this pairing is right.
    // =====================================================================
    printf("\n--- 7. every temperature unit round-trips back to the device's own integer ---\n");
    {
        float backC = convertTemperature(lastStableC, TemperatureUnit::CELSIUS,
                                         ConversionDirection::TO_INTERNAL);
        float backF = convertTemperature(lastStableF, TemperatureUnit::FAHRENHEIT,
                                         ConversionDirection::TO_INTERNAL);
        float backK = convertTemperature(lastStableK, TemperatureUnit::KELVIN,
                                         ConversionDirection::TO_INTERNAL);
        printf("   last stable raw %d: C %.3f -> %.4f, F %.3f -> %.4f, K %.3f -> %.4f\n",
               (int)lastStableRawT, (double)lastStableC, (double)backC,
               (double)lastStableF, (double)backF, (double)lastStableK, (double)backK);

        // Gated on cleanT, not stableT, for the same reason section 4 is gated
        // on cleanV: lastStable{C,F,K} come only from a trial in which all
        // three units matched the same raw integer, so the round-trip cannot
        // fail merely because the sensor stepped mid-bracket.
        TEST_RESULT("the CELSIUS reading converts back to the raw degrees the device sent",
                    cleanT > 0 && std::fabs(backC - (float)lastStableRawT) <= TOL_DEGC);
        TEST_RESULT("the FAHRENHEIT reading converts back to the raw degrees the device sent",
                    cleanT > 0 && std::fabs(backF - (float)lastStableRawT) <= TOL_DEGC);
        TEST_RESULT("the KELVIN reading converts back to the raw degrees the device sent",
                    cleanT > 0 && std::fabs(backK - (float)lastStableRawT) <= TOL_DEGC);
        TEST_RESULT("Celsius recovered from Fahrenheit and from Kelvin agree with the Celsius reading",
                    cleanT > 0 && std::fabs(backF - backC) <= TOL_DEGC &&
                    std::fabs(backK - backC) <= TOL_DEGC);

        // The temperature unit, like the voltage unit, lives in the library.
        m->setTemperatureUnit(TemperatureUnit::KELVIN);
        tfhReset(m);
        delay(200);
        float kAfterReset = m->getTemperature();
        bool ok = (m->getError() == 0);
        m->setTemperatureUnit(TemperatureUnit::CELSIUS);
        printf("   after a device reset, still reading %.2f K\n", (double)kAfterReset);
        TEST_RESULT("the temperature unit is a library setting and survives a device reset",
                    ok && kAfterReset > 250.0f && kAfterReset < 600.0f);
    }

    // =====================================================================
    // 8. THE RELATIONSHIPS STILL HOLD WHILE THE PLANNER IS BUSY. Telemetry is
    //    at its most useful during motion -- that is when a supply sags or a
    //    driver heats up -- and that is also when a reply could plausibly be
    //    assembled from a stale or half-updated ADC buffer, or a response get
    //    mismatched against the wrong request under bus load. Reading the
    //    same quantity in two units mid-move and requiring them to agree is a
    //    much sharper probe of that than a plausibility band would be.
    //
    //    The MOSFETs stay OFF: only the COMMANDED position advances, so
    //    nothing turns. tfhFreshOpen raises the deviation window first, since
    //    with the output stage off the shaft never follows and the default
    //    two-rotation window would otherwise fault a longer move. The move is
    //    drained with tfhDrain, never a computed wait.
    // =====================================================================
    printf("\n--- 8. the conversions still hold while a move is in flight ---\n");
    {
        tfhFreshOpen(m);
        m->setVoltageUnit(VoltageUnit::VOLTS);
        m->setTemperatureUnit(TemperatureUnit::CELSIUS);

        int64_t before = m->getPositionRaw();
        m->trapezoidMoveRaw((int32_t)(TFH_CPR / 2), 2 * TFH_TPS);
        bool accepted = (m->getError() == 0);

        int samples = 0, tSamples = 0;
        int voltsExact = 0, celsiusExact = 0, fahrenheitExact = 0;
        float worstV = 0.0f, worstC = 0.0f, worstF = 0.0f;
        bool allAnswered = accepted;
        for (int i = 0; i < 8 && accepted; i++) {
            uint16_t rawV = m->getSupplyVoltageRaw();
            bool ok = (m->getError() == 0);
            m->setVoltageUnit(VoltageUnit::VOLTS);
            float v = m->getSupplyVoltage();
            ok = ok && (m->getError() == 0);
            uint16_t rawV2 = m->getSupplyVoltageRaw();
            ok = ok && (m->getError() == 0);

            int16_t rawT = m->getTemperatureRaw();
            ok = ok && (m->getError() == 0);
            m->setTemperatureUnit(TemperatureUnit::CELSIUS);
            float c = m->getTemperature();
            ok = ok && (m->getError() == 0);
            m->setTemperatureUnit(TemperatureUnit::FAHRENHEIT);
            float f = m->getTemperature();
            ok = ok && (m->getError() == 0);
            int16_t rawT2 = m->getTemperatureRaw();
            ok = ok && (m->getError() == 0);
            m->setTemperatureUnit(TemperatureUnit::CELSIUS);

            if (!ok) { allAnswered = false; break; }
            // Same best-of-N / bounded pairing as sections 2, 3 and 6: the
            // bracket proves the endpoints agreed, not that the reading never
            // moved and came back, and this is the noisiest moment in the
            // module because the planner is running.
            if (rawV == rawV2) {
                samples++;
                float e = std::fabs(v - (float)rawV / 10.0f);
                if (e > worstV) worstV = e;
                if (e <= TOL_VOLTS) voltsExact++;
            }
            if (rawT == rawT2) {
                tSamples++;
                float eC = std::fabs(c - (float)rawT);
                float eF = std::fabs(f - ((float)rawT * 1.8f + 32.0f));
                if (eC > worstC) worstC = eC;
                if (eF > worstF) worstF = eF;
                if (eC <= TOL_DEGC) celsiusExact++;
                if (eF <= TOL_DEGF) fahrenheitExact++;
            }
            delay(60);
        }

        bool drained = accepted && tfhDrain(m, 15000);
        uint8_t fat = tfhFatal(m);
        int64_t moved = (drained && fat == 0) ? (m->getPositionRaw() - before) : 0;
        printf("   move accepted=%d, %d stable voltage / %d stable temperature in-flight samples "
               "(%d/%d/%d exact V/C/F), moved %lld of %lld, fatal=%u\n",
               (int)accepted, samples, tSamples, voltsExact, celsiusExact, fahrenheitExact,
               (long long)moved, (long long)(TFH_CPR / 2), (unsigned)fat);

        // Asserted separately so that a move which was never accepted shows up
        // as its own root cause instead of only as a cascade of in-flight
        // sampling failures.
        TEST_RESULT("the in-flight move was accepted", accepted);
        TEST_RESULT("telemetry answers every time throughout a move", allAnswered);
        TEST_RESULT("at least one in-flight sample caught the supply holding still", samples > 0);
        TEST_RESULT("VOLTS still equals the raw decivolts divided by ten on at least one in-flight sample",
                    voltsExact > 0);
        TEST_RESULT("no in-flight sample's volts disagreed with the raw decivolts by more than a couple of sensor steps",
                    samples > 0 && worstV <= TOL_VOLTS_BOUND);
        // "Did the temperature bracket ever close" is asserted on its own, so a
        // sensor that never held still produces one clearly-labelled failure
        // instead of three confusing ones. The exactness claims are then
        // written so they cannot fail for that reason -- the same structure the
        // rest of the module uses.
        TEST_RESULT("at least one in-flight sample caught the temperature holding still", tSamples > 0);
        TEST_RESULT("CELSIUS still equals the raw degrees on at least one in-flight sample",
                    tSamples == 0 || celsiusExact > 0);
        TEST_RESULT("FAHRENHEIT still equals Celsius times 1.8 plus 32 on at least one in-flight sample",
                    tSamples == 0 || fahrenheitExact > 0);
        TEST_RESULT("no in-flight temperature sample disagreed by more than a couple of sensor steps",
                    tSamples == 0 || (worstC <= TOL_DEGC_BOUND && worstF <= TOL_DEGF_BOUND));
        TEST_RESULT("polling telemetry throughout the move did not disturb it",
                    drained && fat == 0 &&
                    llabs((long long)(moved - TFH_CPR / 2)) <= TFH_CPR / 200);
    }

    // Restore the library's factory-default units (Servomotor.h:558-559) so the
    // next module starts from the same place, and leave the machine reset.
    m->setVoltageUnit(VoltageUnit::VOLTS);
    m->setTemperatureUnit(TemperatureUnit::CELSIUS);
    tfhReset(m);
    TEST_RESULT("the motor is left clean", tfhFatal(m) == 0);
}
