#ifndef __GOERTZEL_ALGORITHM_CONSTANTS__
#define __GOERTZEL_ALGORITHM_CONSTANTS__

// This file is autogenerated by the program called go_to_closed_loop_mode_calculations_and_table_output.py
// * * * DO NOT EDIT * * * Instead, edit the program that autogenerates this

#define DESIRED_MOTOR_PWM_VOLTAGE_SHIFT 1
#define GO_TO_CLOSED_LOOP_MOTOR_PWM_VOLTAGE (80 << DESIRED_MOTOR_PWM_VOLTAGE_SHIFT)
#define DESIRED_MOTOR_PWM_VOLTAGE_STEP 8
#define GO_TO_CLOSED_LOOP_SHIFT_RIGHT (DESIRED_MOTOR_PWM_VOLTAGE_SHIFT)
#define GO_TO_CLOSED_LOOP_PHASE_ADJUSTMENT_SAMPLES (2)
#define GO_TO_CLOSED_LOOP_AVERAGE_SAMPLES 100

#define W_REAL_MULTIPLIER 2090687
#define W_REAL_SHIFT 20
#define W_IMAG_MULTIPLIER 82270
#define W_IMAG_SHIFT 20

#endif
