// THIS FILE IS AUTOGENERATED
// Do not edit this directly
#include "product_info.h"

struct product_info_struct *get_product_info(void)
{
    return (struct product_info_struct *)PRODUCT_INFO_MEMORY_LOCATION;
}
