#ifndef COMMANDS_H_
#define COMMANDS_H_

#define DISABLE_MOSFETS_COMMAND 0
#define ENABLE_MOSFETS_COMMAND 1
#define SET_POSITION_AND_MOVE_COMMAND 2
#define SET_VELOCITY_COMMAND 3
#define SET_POSITION_AND_FINISH_TIME_COMMAND 4
#define SET_ACCELERATION_COMMAND 5
#define START_CALIBRATION_COMMAND 6
#define CAPTURE_HALL_SENSOR_DATA_COMMAND 7
#define RESET_TIME_COMMAND 8
#define GET_CURRENT_TIME_COMMAND 9
#define TIME_SYNC_COMMAND 10
#define GET_N_ITEMS_IN_QUEUE_COMMAND 11
#define EMERGENCY_STOP_COMMAND 12
#define ZERO_POSITION_COMMAND 13
#define HOMING_COMMAND 14
#define GET_POSITION_COMMAND 15
#define GET_STATUS_COMMAND 16
#define GO_TO_CLOSED_LOOP_COMMAND 17
#define GET_UPDATE_FREQUENCY_COMMAND 18
#define MOVE_WITH_ACCELERATION_COMMAND 19
#define DETECT_DEVICES_COMMAND 20
#define SET_DEVICE_ALIAS_COMMAND 21
#define GET_PRODUCT_INFO_COMMAND 22
#define FIRMWARE_UPGRADE_COMMAND 23
#define NO_ERROR_RESPONSE "R\x00\x00"

#endif