#ifndef COMMANDS_H_
#define COMMANDS_H_

#define ADD_NEW_INTERVAL_COMMAND 0
#define SET_INTERVAL_RUN_MODE_COMMAND 1
#define RESET_TIME_COMMAND 8
#define GET_CURRENT_TIME_COMMAND 9
#define TIME_SYNC_COMMAND 10
#define GET_STATUS_COMMAND 16
#define DETECT_DEVICES_COMMAND 20
#define SET_DEVICE_ALIAS_COMMAND 21
#define GET_PRODUCT_INFO_COMMAND 22
#define FIRMWARE_UPGRADE_COMMAND 23
#define GET_PRODUCT_DESCRIPTION_COMMAND 24
#define GET_FIRMWARE_VERSION_COMMAND 25
#define SYSTEM_RESET_COMMAND 27
#define PING_COMMAND 31
#define GET_DATA_RECORD_COMMAND 32

#define ADD_TO_QUEUE_TEST_COMMAND 254

#define NO_ERROR_RESPONSE "R\x00\x00"

#endif